@extends('layoutIndicadoresF')
@section('head')
@stop

@section('title')
  Indicadores Fiscales | Vázquez Hernández Contadores, S. C.
@stop

@section('body')
@stop

@section('content')
<div class="well transparenteClaroTxt">
  <div class="row">
    <div class="col-md-12">

        <div  class="table-responsive">
            <table class="table table-striped  table-bordered table-condensed">

              <!-- **************** -->
			<h3 class="text-center">	Tabla de actualización de multas por infracciones relacionadas con las disposiciones fiscales	</h3>

<thead>
	<tr  class="activoLiMenu">	<th colspan="6"class="text-center">	CÓDIGO FISCAL DE LA FEDERACIÓN	</th>	</tr>
	<tr  class="activoLiMenu">	<th class="text-center">	VIGENCIA	</th>	<th class="text-center">		</th>	<th class="text-center">		</th>	<th class="text-center">	Del 1o./ene/2012 al 31/dic/2012	</th>	<th class="text-center">	Del 1o./ene/2013 al 31/dic/2013	</th>	<th class="text-center">	Del 1o./ene/2014 en adelante	</th>	</tr>
	<tr  class="activoLiMenu">	<th class="text-center">		</th>	<th class="text-center">	Fecha de publicación en el DOF	</th>	<th class="text-center">		</th>	<th class="text-center">	10-febrero-2009, 28-diciembre-2009, 31-diciembre-2010 y 05/01/2012	</th>	<th class="text-center">	10-febrero-2009, 28-diciembre-2009, 31-diciembre-2010, 5-enero-2012 y 31-diciembre-2012	</th>	<th class="text-center">	10-febrero-2009, 28-diciembre-2009, 31-diciembre-2010, 5-enero-2012, 31-diciembre-2012 y 3-enero-2014	</th>	</tr>
</thead>

<tbody class="animEscalarFila">
	<tr>	<td rowspan="8">	Artículo 80 Multas relacionadas con el RFC	  </td>	<td>	Fracción I No solicitar la inscripción. No presentar solicitud de inscripción a nombre de un tercero. Señalar domicilio fiscal erróneo	  </td>	<td>		  </td>	<td>	De $2,740.00 a $8,230.00	  </td>	<td>	De $2,740.00 a $8,230.00	  </td>	<td>	De $2,740.00 a $8,230.00	  </td>	</tr>
	<tr>				<td rowspan="2">	Fracción II No presentar avisos al registro	  </td>	<td >	Hasta el 31/dic/13, personas físicas del régimen de pequeños contribuyentes. A partir del 1o./ ene/14, personas físicas del régimen de incorporación fiscal	  </td>	<td >	De $1,010.00 a $2,030.00	  </td>	<td >	De $1,140.00 a $2,280.00	  </td>	<td >	De $1,140.00 a $2,280.00	  </td>	</tr>
	<tr>							<td >	Los demás contribuyentes	  </td>	<td >	De $3,040.00 a $6,070.00	  </td>	<td >	De $3,420.00 a $6,830.00		<td >	De $3,420.00 a $6,830.00	  </td>	</tr>
	<tr>				<td rowspan="2">	Fracción III No citar la clave del registro o utilizar alguna no asignada por la autoridad fiscal	  </td>	<td>	a) Cuando se trate de declaraciones	  </td>	<td>	Entre el 2% de las contribuciones declaradas y $5,830.00. En ningún caso la multa que resulte de aplicar dicho porcentaje será menor de $2,330.00 ni mayor de 5830	  </td>	<td>	Entre el 2% de las contribuciones declaradas y $5,830.00. En ningún caso la multa que resulte de aplicar dicho porcentaje será menor de $2,330.00 ni mayor de 5830	  </td>	<td>	Entre el 2% de las contribuciones declaradas y $5,830.00. En ningún caso la multa que resulte de aplicar dicho porcentaje será menor de $2,330.00 ni mayor de $5,830.00	  </td>	</tr>
	<tr>							<td >	b) En los demás documentos	  </td>	<td >	De $710.00 a $1,630.00	  </td>	<td >	De $710.00 a $1,630.00		<td >	De $710.00 a $1,630.00	  </td>	</tr>
	<tr>				<td>	Fracción IV Por autorización de actas constitutivas, de fusión, escisión o liquidación, de personas morales sin presentación de aviso o solicitud	  </td>	<td>		  </td>	<td>	De $13,720.00 a $27,440.00	  </td>	<td>	De $13,720.00 a $27,440.00	  </td>	<td>	De $13,720.00 a $27,440.00	  </td>	</tr>
	<tr>				<td>	Fracción V No asentar o asentar incorrectamente en las actas de asamblea o libros de socios o accionistas, el RFC de cada socio o accionista	  </td>	<td>		  </td>	<td>	De $2,720.00 a $8,200.00	  </td>	<td>	De $2,720.00 a $8,200.00	  </td>	<td>	De $2,720.00 a $8,200.00	  </td>	</tr>
	<tr>				<td>	Fracción VI No asentar o asentar incorrectamente en las actas constitutivas y demás actas de asamblea de personas morales, la clave del RFC de cada socio o accionista, o no verificar que dicha clave aparezca en tales actas	  </td>	<td>		  </td>	<td>	De $13,650.00 a $27,300.00	  </td>	<td>	De $13,650.00 a $27,300.00	  </td>	<td>	De $13,650.00 a $27,300.00	  </td>	</tr>
	<tr>	<td rowspan="51">	Artículo 82 Multas relacionadas con declaraciones, solicitudes o avisos	  </td>	<td rowspan="5">	Fracción I No presentar declaraciones, solicitudes, avisos o constancias, o no hacerlo mediante medios electrónicos	  </td>	<td>	a) Cuando se trate de declaraciones	  </td>	<td>	De $1,100.00 a $13,720.00 Por cada una de las obligaciones no declaradas	  </td>	<td>	De $1,100.00 a $13,720.00 Por cada una de las obligaciones no declaradas	  </td>	<td>	De $1,100.00 a $13,720.00 Por cada una de las obligaciones no declaradas	  </td>	</tr>
	<tr>							<td>	b)Cuando se trate de requerimien tos atendidos fuera del plazo señalado o por incumplimiento	  </td>	<td>	De $1,100.00 a $27,440.00 Por cada obligación a la que esté afecto	  </td>	<td>	De $1,100.00 a $27,440.00 Por cada obligación a la que esté afecto	  </td>	<td>	De $1,100.00 a $27,440.00 Por cada obligación a la que esté afecto	  </td>	</tr>
	<tr>							<td>	b)Cuando se trate de requerimien tos atendidos fuera del plazo señalado o por incumplimiento	  </td>	<td>	De $10,530.00 a $21,040.00	  </td>	<td>	De $10,530.00 a $21,040.00	  </td>	<td>	De $10,530.00 a $21,040.00	  </td>	</tr>
	<tr>							<td>	c) Cuando se trate del aviso de compensación	  </td>	<td>	De $11,240.00 a $22,500.00	  </td>	<td>	De $11,240.00 a $22,500.00	  </td>	<td>	De $11,240.00 a $22,500.00	  </td>	</tr>
	<tr>							<td>	e) En los demás documentos	  </td>	<td>	De $1,130.00 a $3,600.00	  </td>	<td>	De $1,130.00 a $3,600.00	  </td>	<td>	De $1,130.00 a $3,600.00	  </td>	</tr>
	<tr>				<td rowspan="7">	Fracción II Presentar declaraciones, solicitudes, avisos o constancias, o declaraciones en medios electrónicos incompletos, con errores, omisiones o en forma distinta a lo señalado por las disposiciones fiscales	  </td>	<td>	a) En el nombre, o en el domicilio	  </td>	<td>	De $820.00 a $2,740.00 Por cada uno	  </td>	<td>	De $820.00 a $2,740.00 Por cada uno	  </td>	<td>	De $820.00 a $2,740.00 Por cada uno	  </td>	</tr>
	<tr>							<td>	b) Por cada dato no asentado o asentado incorrectamente, en la relación de clientes y proveedores presentado	  </td>	<td>	De $30.00 a $70.00	  </td>	<td>	De $30.00 a $70.00	  </td>	<td>	De $30.00 a $70.00	  </td>	</tr>
	<tr>							<td>	 c)Por cada dato adicional. Tratándose de la omisión de la presentación de anexos, por cada dato que contenga el anexo no	  </td>	<td>	De $150.00 a $270.00	  </td>	<td>	De $150.00 a $270.00	  </td>	<td>	De $150.00 a $270.00	  </td>	</tr>
	<tr>							<td>	d) En la clave de la actividad preponderante	  </td>	<td>	De $550.00 a $1,370.00	  </td>	<td>	De $550.00 a $1,370.00	  </td>	<td>	De $550.00 a $1,370.00	  </td>	</tr>
	<tr>							<td>	e) En los medios electrónicos	  </td>	<td>	De $3,360.00 a $11,240.00	  </td>	<td>	De $3,360.00 a $11,240.00	  </td>	<td>	De $3,360.00 a $11,240.00	  </td>	</tr>
	<tr>							<td>	f) Por no presentar firmadas las de claraciones por el contribuyente o por el representante legal	  </td>	<td>	De $1,000.00 a $2,980.00	  </td>	<td>	De $1,000.00 a $2,980.00	  </td>	<td>	De $1,000.00 a $2,980.00	  </td>	</tr>
	<tr>							<td>	g) En los demás casos	  </td>	<td>	De $500.00 a $1,350.00	  </td>	<td>	De $500.00 a $1,350.00	  </td>	<td>	De $500.00 a $1,350.00	  </td>	</tr>
	<tr>				<td>	Fracción III No pagar contribuciones dentro del plazo	  </td>	<td>	Por cada requerimiento	  </td>	<td>	De $1,100.00 a $27,440.00 Por cada obligación a la que esté afecto	  </td>	<td>	De $1,100.00 a $27,440.00 Por cada obligación a la que esté afecto	  </td>	<td>	De $1,100.00 a $27,440.00 Por cada obligación a la que esté afecto	  </td>	</tr>
	<tr>				<td rowspan="2">	Fracción IV Pago provisional no efectuado en los términos de las disposiciones fiscales. En caso de quien los efectúe	  </td>	<td>	a) Mensualmente	  </td>	<td>	De $13,720.00 a $27,440.00	  </td>	<td>	De $13,720.00 a $27,440.00	  </td>	<td>	De $13,720.00 a $27,440.00	  </td>	</tr>
	<tr>						  </td>	<td>	b) Trimestral o cuatrimestralmente	  </td>	<td>	De $1,370.00 a $8,230.00	  </td>	<td>	De $1,370.00 a $8,230.00	  </td>	<td>	De $1,370.00 a $8,230.00	  </td>	</tr>
	<tr>				<td>	Fracción V No proporcionar la información de las personas a las que se les hubieran entregado cantidades en efectivo por concepto de subsidio para el empleo	  </td>	<td>		  </td>	<td>	De $9,430.00 a $18,860.00	  </td>	<td>	De $9,430.00 a $18,860.00	  </td>	<td>	De $9,430.00 a $18,860.00	  </td>	</tr>
	<tr>				<td>	Fracción VI No presentar aviso de cambio de domicilio	  </td>	<td>		  </td>	<td>	De $2,740.00 a $8,230.00	  </td>	<td>	De $2,740.00 a $8,230.00	  </td>	<td>	De $2,740.00 a $8,230.00	  </td>	</tr>
	<tr>				<td>	VII No presentar la información manifestando las razones por las cuales no se determina impuesto a pagar o saldo a favor	  </td>	<td>		  </td>	<td>	De $680.00 a $6,920.00	  </td>	<td>	De $680.00 a $6,920.00	  </td>	<td>	De $680.00 a $6,920.00	  </td>	</tr>
	<tr>				<td>	Fracción VIII No presentar los datos o informes, según la Ley del Impuesto sobre Tenencia o Uso de Vehículos, o la Ley del IEPS	  </td>	<td>		  </td>	<td>	De $52,060.00 a $156,180.00	  </td>	<td>	De $52,060.00 a $156,180.00	  </td>	<td>	De $52,060.00 a $156,180.00	  </td>	</tr>
	<tr>				<td>	Fracción IX No presentar las declaraciones para fines estadísticos	  </td>	<td>		  </td>	<td>	De $8,230.00 a $27,440.00	  </td>	<td>	De $8,230.00 a $27,440.00	  </td>	<td>	De $8,230.00 a $27,440.00	  </td>	</tr>
	<tr>				<td>	Fracción X No remitir al SAT los comprobantes fiscales digitales para la validación los requisitos fiscales  y asignar el folio del comprobante.	  </td>	<td>		  </td>	<td>	De $8,000.00 a $15,000.00	  </td>	<td>	De $8,000.00 a $15,000.00	  </td>	<td>	De $8,940.00 a $16,750.00	  </td>	</tr>
	<tr>				<td>	Fracción XI Hasta el 31/dic/13, por cada sociedad controlada no incluida en la solicitud de autorización para determinar el resultado fiscal consolidado, o no incorporada a la consolidación fiscal. A partir del 1o./ene/14, por cada sociedad integrada no incluida en la solicitud de autorización para determinar el resultado fiscal integrado o no incorporada en el régimen opcional para grupo de sociedades	  </td>	<td>		  </td>	<td>	De $104,580.00 a $139,450.00	  </td>	<td>	De $104,580.00 a $139,450.00	  </td>	<td>	De $104,580.00 a $139,450.00	  </td>	</tr>
	<tr>				<td>	Fracción XII Hasta el 31/dic/13, por cada aviso de desincorporación o incorporación al régimen de consolidación fiscal no presentado o extemporáneo. A partir del 1o./ene/14, por cada aviso de desincorporación o incorporación al régimen opcional para grupos de sociedades no presentado o extemporáneo	  </td>	<td>		  </td>	<td>	De $35,670.00 a $54,900.00	  </td>	<td>	De $35,670.00 a $54,900.00	  </td>	<td>	De $35,670.00 a $54,900.00	  </td>	</tr>
	<tr>				<td>	Fracción XIII No presentar declaración de donativos otorgados	  </td>	<td>		  </td>	<td>	De $8,230.00 a $27,440.00	  </td>	<td>	De $8,230.00 a $27,440.00	  </td>	<td>	No aplica	  </td>	</tr>
	<tr>				<td>	Fracción XIV No presentar declaración de operaciones realizadas mediante fideicomisos	  </td>	<td>		  </td>	<td>	De $8,230.00 a $19,200.00	  </td>	<td>	De $8,230.00 a $19,200.00	  </td>	<td>	De $8,230.00 a $19,200.00	  </td>	</tr>
	<tr>				<td>	Fracción XV No proporcionar la información de inversiones en empresas promovidas	  </td>	<td>		  </td>	<td>	De $68,620.00 a $137,230.00	  </td>	<td>	De $68,620.00 a $137,230.00	  </td>	<td>	No aplica	  </td>	</tr>
	<tr>				<td>	Fracción XVI No proporcionar la información a que se refiere la fracción V del artículo 32 de la Ley del IVA a través de los medios, formatos electrónicos y plazos establecidos en dicha ley, o presentarla incompleta o con errores	  </td>	<td>		  </td>	<td>	De $9,920.00 a $19,840.00	  </td>	<td>	De $9,920.00 a $19,840.00	  </td>	<td>	De $9,920.00 a $19,840.00 En caso de reincidencia la multa aumentará al 100% por cada nuevo incumplimiento	  </td>	</tr>
	<tr>				<td>	Fracción XVII No presentar declaración informativa de las operaciones efectuadas con partes relaciona das residentes en el extranjero, o presentarla incompleta o con errores	  </td>	<td>		  </td>	<td>	De $61,000.00 a $122,010.00	  </td>	<td>	De $61,000.00 a $122,010.00	  </td>	<td>	De $61,000.00 a $122,010.00	  </td>	</tr>
	<tr>				<td rowspan="2">	Fracción XVIII	  </td>	<td>	No presentar relación de trasladado en forma expresa y por separadoel IEPS, así como no proporcionar el precio de enajenación de cada producto, valor y volumendel trimestre anterior	  </td>	<td>	De $7,780.00 a $12,960.00	  </td>	<td>	De $7,780.00 a $12,960.00	  </td>	<td>	De $7,780.00 a $12,960.00	  </td>	</tr>
	<tr>							<td>	No proporcionar reporte de los números de folio de marbetes y precintos obtenidos,  utilizados y destruidos, así como el que contenga número de  litros enajenados en el trimestre anterior	  </td>	<td>	De $7,780.00 a $12,960.00	  </td>	<td>	De $7,780.00 a $12,960.00	  </td>	<td>	De $7,780.00 a $12,960.00	  </td>	</tr>
	<tr>				<td>	Fracción XIX No presentar la información de la lectura mensual de registros utilizados para llevar un control físico del volumen fabricado, producido o envasado. No informar de la lectura mensual de registros de cada uno de los contadores utilizados para llevar un control volumétrico, ni reportar el número de litros producidos	  </td>	<td>		  </td>	<td>	De $12,960.00 a $25,930.00	  </td>	<td>	De $12,960.00 a $25,930.00	  </td>	<td>	De $12,960.00 a $25,930.00	  </td>	</tr>
	<tr>				<td>	Fracción XX No presentar el aviso de cambio de residencia fiscal, por parte de personas físicas o morales que dejen de ser residentes en México	  </td>	<td>		  </td>	<td>	De $4,150.00 a $8,310.00	  </td>	<td>	De $4,150.00 a $8,310.00	  </td>	<td>	De $4,150.00 a $8,310.00	  </td>	</tr>
	<tr>				<td>	Fracción XXI No inscribirse en los padrones de contribuyentes que establece la Ley del IEPS	  </td>	<td>		  </td>	<td>	De $99,260.00 a $198,540.00	  </td>	<td>	De $99,260.00 a $198,540.00	  </td>	<td>	De $99,260.00 a $198,540.00	  </td>	</tr>
	<tr>				<td>	Fracción XXII No proporcionar la información relativa al interés real pagado por el contribuyente en el ejercicio de que se trate por créditos hipotecarios	  </td>	<td>		  </td>	<td>	De $4,150.00 a $8,310.00 Por cada informe no proporcionado a los contribuyentes	  </td>	<td>	De $4,150.00 a $8,310.00 Por cada informe no proporcionado a los contribuyentes	  </td>	<td>	 De $4,150.00 a $8,310.00 Por cada informe no proporcionado a los contribuyentes	  </td>	</tr>
	<tr>				<td>	Fracción XXIII No proporcionar o presentar con errores la información sobre adquisiciones o enajenaciones, realizadas a empresas con programas de importación temporal o maquiladoras	  </td>	<td>		  </td>	<td>	De $11,910.00 a $21,830.00	  </td>	<td>	De $11,910.00 a $21,830.00	  </td>	<td>	De $11,910.00 a $21,830.00	  </td>	</tr>
	<tr>				<td>	Fracción XXIV No proporcionar la constancia en la que se manifieste el monto nominal y real de los intereses pagados o, en su caso, la pérdida determinada	  </td>	<td>		  </td>	<td>	De $4,150.00 a $8,310.00 por cada constancia no proporcionada	  </td>	<td>	De $4,150.00 a $8,310.00 por cada constancia no proporcionada	  </td>	<td>	 De $4,150.00 a $8,310.00 por cada constancia no proporcionada	  </td>	</tr>
	<tr>				<td>	Fracción XXV Hasta el 31/dic/13 no contar con los controles volumétricos a que se refiere el artículo 28, fracción V, del CFF, o no mantenerlos en todo momento en operación. A partir del 1o./ene/14 no cumplir con lo establecido en la fracción I, del CFF, o que los controles volumétricos presenten alguna inconsistencia en su funciona miento y medición	  </td>	<td>		  </td>	<td>	De $27,680.00 a $48,440.00 En caso de reincidencia, la sanción consistirá en la clausura del establecimiento del contribuyente, por un plazo de 3 a 15 días	  </td>	<td>	De $27,680.00 a $48,440.00 En caso de reincidencia, la sanción consistirá en la clausura del establecimiento del contribuyente, por un plazo de  3 a 15 días	  </td>	<td>	De $27,680.00 a $48,440.00 En caso de reincidencia, la sanción consistirá en la clausura del establecimiento del contribuyente, por un plazo de 3 a 15 días	  </td>	</tr>
	<tr>				<td>	Fracción XXVI No proporcionar la información a que se refiere la fracción VIII del artículo 32 de la Ley del IVA a través de los medios, formatos electrónicos y plazos incompleta o con errores.establecidos en dicha Ley, o presentarla	  </td>	<td>		  </td>	<td>	De $9,430.00 a $18,860.00	  </td>	<td>	De $9,430.00 a $18,860.00	  </td>	<td>	De $9,430.00 a $18,860.00. En caso de reincidencia la multa aumentará al 100% por cada nuevo incumplimiento	  </td>	</tr>
	<tr>				<td>	Fracción XXVII No proporcionar la información a que se refiere el artículo 32-G del CFF, a través de los medios, formatos electrónicos y plazos establecidos en dicha Ley, o presentarla incompleta o con errores.	  </td>	<td>		  </td>	<td>	De $9,430.00 a $18,860.00	  </td>	<td>	De $9,430.00 a $18,860.00	  </td>	<td>	De $9,430.00 a $18,860.00	  </td>	</tr>
	<tr>				<td>	Fracción XXVIII Hasta el 31/dic/13, no cumplir con la obligación a que se refiere la fracción IV del artículo 117 de la Ley del ISR. A partir del 1o./ene/14, no cumplir con la obligación a que se refiere la fracción IV del artículo 98 de la Ley del ISR	  </td>	<td>		  </td>	<td>	De $570.00 a $860.00	  </td>	<td>	De $570.00 a $860.00	  </td>	<td>	De $570.00 a $860.00	  </td>	</tr>
	<tr>				<td>	Fracción XXIX Hasta el 31/dic/13, no proporcionar la informa ción señalada en el cuarto párrafo del artículo 30-A del CFF o presentarla incompleta o con errores. A partir del 1o./ene/14, no proporcionar la información señalada en el artículo 30-A del CFF o presentarla incompleta o con errores	  </td>	<td>		  </td>	<td>	De $38,200.00 a $191,000.00 En caso de reincidencia, la multa será de $76,400.00 a $382,000.00 por cada requerimiento que se formule	  </td>	<td>	De $38,200.00 a $191,000.00 En caso de reincidencia, la multa será de $76,400.00 a $382,000.00 por cada requerimiento que se formule	  </td>	<td>	De $38,200.00 a $191,000.00 En caso de reincidencia, la multa será de $76,400.00 a $382,000.00 por cada requerimiento que se formule	  </td>	</tr>
	<tr>				<td>	Fracción XXX Hasta el 31/dic/13, no proporcionar o proporcionar de forma extemporánea la documentación comprobatoria que ampare que las acciones objeto de la autorización a que se refiere el artículo 190 de la Ley del ISR, no han salido del grupo de sociedades o no presentar o presentar en forma extemporánea la información o el aviso a que se refieren los artículos 262, fracción IV, y 269 del Reglamento de la Ley del ISR. A partir del 1o./ene/14, no proporcionar o proporcionar de forma extemporánea la documentación comprobatoria que ampare que las acciones objeto de la autorización a que se refiere el artículo 161 de la Ley del ISR, no han salido del grupo de sociedades o no presentar o presentar en forma extemporánea la información o el aviso a que se refieren los artículos 262, fracción IV, y 269 del Reglamento de la Ley del ISR	  </td>	<td>		  </td>	<td>	De $124,990.00 a $177,950.00	  </td>	<td>	De $124,990.00 a $177,950.00	  </td>	<td>	De $124,990.00 a $177,950.00	  </td>	</tr>
	<tr>				<td>	Fracción XXXI Hasta el 31/dic/13, no proporcionar la información a que se refieren los artículos 86, fracción XIX, 97, fracción VI, 133 fracción VII, 145, fracción V, y 154-TER de la Ley del ISR, o presentarla en forma extemporánea. A partir del 1o./ene/14, no proporcionar la información a que se refieren los artículos 76, fracción XV, 82, fracción VII, 110, fracción VII, 118, fracción V, y 128 de la Ley del ISR, o presentarla en forma extemporánea	  </td>	<td>		  </td>	<td>	De $124,990.00 a $177,950.00	  </td>	<td>	De $124,990.00 a $177,950.00	  </td>	<td>	De $124,990.00 a $177,950.00	  </td>	</tr>
	<tr>				<td>	Fracción XXXII No proporcionar trimestralmente al SAT a través de medios electrónicos, la información correspondiente a los comprobantes fiscales que hayan expedido los contribuyentes con los folios asignados por dicho órgano.	  </td>	<td>		  </td>	<td>	De $8,000.00 a $15,000.00	  </td>	<td>	De $8,000.00 a $15,000.00	  </td>	<td>	No aplica	  </td>	</tr>
	<tr>				<td>	Fracción XXIII No proporcionar o presentar con errores la información sobre adquisiciones o enajenaciones, realizadas a empresas con programas de importación temporal o maquiladoras	  </td>	<td>		  </td>	<td>	De $8,000.00 a $15,000.00	  </td>	<td>	De $8,000.00 a $15,000.00	  </td>	<td>	No aplica	  </td>	</tr>
	<tr>				<td>	Fracción XXXIV No proporcionar los datos, informes o documentos solicitados por las autoridades fiscales conforme a lo previsto en el primer párrafo del artículo 42-A del CFF.	  </td>	<td>		  </td>	<td>	De $11,910.00 a $21,830.00	  </td>	<td>	De $11,910.00 a $21,830.00	  </td>	<td>	De $11,910.00 a $21,830.00	  </td>	</tr>
	<tr>				<td>	Fracción XXXV A partir de 2012, utilizar dispositivos de seguridad que no se encuentren vigentes Antes, no destruir los dispositivos de seguridad de los comprobantes digitales no utilizados, así como no presentar el aviso correspondiente de la destrucción	  </td>	<td>		  </td>	<td>	De $8,000.00 a $15,000.00 Por cada dispositivo de seguridad que se utilice sin que se encuentre vigente	  </td>	<td>	De $8,000.00 a $15,000.00 Por cada dispositivo de seguridad que se utilice sin que se encuentre vigente	  </td>	<td>	No aplica	  </td>	</tr>
	<tr>				<td>	Fracción XXXVI No cumplir con las obligaciones establecidas en el artículo 82, fracción III, y penúltimo párrafo, inciso a, de la Ley del ISR.	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $80,000.00 a $100,000.00. En su caso, la cancelación de la autorización para recibir donativos	  </td>	</tr>
	<tr>				<td>	Fracción XXVII No cumplir con las obligaciones establecidas en el artículo 82, fracción III y penúltimo párrafo, inciso b), de la Ley del Impuesto sobre la Renta.	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $80,000.00 a $100,000.00 En su caso, la cancelación de la autorización para recibir donativos	  </td>	</tr>
	<tr>				<td>	Fracción XXVIII No desarrollen las actividades que tengan como finalidad primordial el cumplimiento de su objeto social	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $80,000.00 a $100,000.00 En su caso, la cancelación de la autorización para recibir donativos	  </td>	</tr>
	<tr>				<td>	 Fracción XXXIX Que al momento de su liquidación no destinen la totalidad de su patrimonio a entidades autorizadas para recibir donativos deducibles	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $80,000.00 a $100,000.00. En su caso, la cancelación de la autorización para recibir donativos	  </td>	</tr>
	<tr>	<td rowspan="18">	Artículo 84 Multas relacionadas con la contabilidad	  </td>	<td>	Fracción I No llevar contabilidad	  </td>	<td>		  </td>	<td>	De $1,200.00 a $11,960.00	  </td>	<td>	De $1,200.00 a $11,960.00	  </td>	<td>	De $1,200.00 a $11,960.00	  </td>	</tr>
	<tr>				<td>	Fracción II No llevar libros o registros, no valuar o controlar inventarios, y llevar la contabilidad en forma o lugar distinto	  </td>	<td>		  </td>	<td>	De $260.00 a $5,980.00	  </td>	<td>	De $260.00 a $5,980.00	  </td>	<td>	De $260.00 a $5,980.00	  </td>	</tr>
	<tr>				<td>	Fracción III No hacer asientos contables o hacerlos incompletos, inexactos o fuera de plazo	  </td>	<td>		  </td>	<td>	De $260.00 a $4,790.00	  </td>	<td>	De $260.00 a $4,790.00	  </td>	<td>	De $260.00 a $4,790.00	  </td>	</tr>
	<tr>				<td rowspan="3">	 Fracción IV No expedir o no entregar comprobante de sus actividades, o expedirlos sin requisitos fiscales	  </td>	<td>	Hasta el 31/dic/13, personas físicas del régimen de pequeños contribuyentes. A partir del 1o./ ene/14, personas físicas del régimen de incorporación fiscal	  </td>	<td>	De $1,210.00 a $2,410.00 En caso de reincidencia, adicionalmente se podrá clausurar preventivamente el establecimiento del contribuyentes de 3 a 15 días	  </td>	<td>	De $1,210.00 a $2,410.00 En caso de reincidencia, adicinalmente se podrá clausurar preventivamente el establecimiento del contribuyentes de 3 a 15 días	  </td>	<td>	De $1,210.00 a $2,410.00 En caso de reincidencia, adicionalmente se podrá clausurar preventivamente el establecimiento del contribuyentes de 3 a 15 días	  </td>	</tr>
	<tr>						  </td>	<td>	Los demás contribuyentes	  </td>	<td>	De $12,070.00 a $69,000.00 En caso de reincidencia, adicionalmente se podrá clausurar preventivamente el establecimiento del contribuyentes de 3 a 15 días	  </td>	<td>	De $12,070.00 a $69,000.00 En caso de reincidencia, adicionalmente se podrá clausurar preventivamente el establecimiento del contribuyentes de 3 a 15 días	  </td>	<td>	De $12,070.00 a $69,000.00 En caso de reincidencia, adicionalmente se podrá clausurar preventivamente el establecimiento del contribuyentes de 3 a 15 días	  </td>	</tr>
	<tr>						  </td>	<td>	Donatarias	  </td>	<td>	De $12,070.00 a $69,000.00 En caso de reincidencia, además se revocará la autorización para recibir donativos deducibles	  </td>	<td>	 De $12,070.00 a $69,000.00 En caso de reincidencia, además se revocará la autorización para recibir donativos deducibles	  </td>	<td>	 De $12,070.00 a $69,000.00 En caso de reincidencia, además se revocará la autorización para recibir donativos deducibles	  </td>	</tr>
					<td>	Fracción V No conservar la contabilidad en el plazo establecido por las disposiciones fiscales	  </td>	<td>		  </td>	<td>	De $730.00 a $9,560.00	  </td>	<td>	De $730.00 a $9,560.00	  </td>	<td>	De $730.00 a $9,560.00	  </td>	</tr>
	<tr>				<td rowspan="2">	Fracción VI Expedir comprobantes fiscales con datos distintos al del adquirente arrendatario o prestatario, cuando se trate de la primera infracción	  </td>	<td>	Hasta el 31/dic/13, personas físicas del régimen de pequeños contribuyentes. A partir del 1o./ ene/14, personas físicas del régimen de incorporación fiscal	  </td>	<td>	De $1,210.00 a $2,410.00 En caso de reincidencia, la sanción será la clausura preventiva del establecimiento del contribuyente de 3 a 15 días	  </td>	<td>	De $1,360.00 a $2,710.00 En caso de reincidencia, la sanción será la clausura preventiva del establecimiento del contribuyente de 3 a 15 días	  </td>	<td>	De $730.00 a $9,560.00	  </td>	</tr>
	<tr>						  </td>	<td>	Los demás contribuyentes	  </td>	<td>	De $12,070.00 a $69,000.00 En caso de reincidencia, la sanción será la clausura preventiva del establecimiento del contribuyente de 3 a 15 días	  </td>	<td>	De $13,570.00 a $77,600.00 En caso de reincidencia, la sanción será la clausura preventiva del establecimiento del contribuyente de 3 a 15 días	  </td>	<td>	De $13,570.00 a $77,600.00 En caso de reincidencia, la sanción será la clausura preventiva del establecimiento del contribuyente de 3 a 15 días	  </td>	</tr>
	<tr>				<td>	Fracción VII Microfilmar o grabar en discos ópticos, información sin cumplir con los requisitos establecidos	  </td>	<td>		  </td>	<td>	De $2,400.00 a $11,960.00	  </td>	<td>	De $2,400.00 a $11,960.00	  </td>	<td>	No aplica	  </td>	</tr>
	<tr>				<td>	Fracción VIII No tener en operación o no registrar el valor de los actos o actividades con el público en general, en los equipos y sistemas electrónicos de registro fiscal autorizado	  </td>	<td>		  </td>	<td>	De $5,490.00 a $27,440.00	  </td>	<td>	De $5,490.00 a $27,440.00	  </td>	<td>	De $5,490.00 a $27,440.00	  </td>	</tr>
	<tr>				<td>	Fracción IX Hasta el 31/dic/13, no dictaminar los estados financieros, estando obligado, o no presentar dictamen. A partir del 1o./ene/14, no dictaminar los estados financieros cuando se hubiera optado por hacerlo o no presentar dicho dictamen	  </td>	<td>		  </td>	<td>	De $10,980.00 a $109,790.00	  </td>	<td>	De $10,980.00 a $109,790.00	  </td>	<td>	De $10,980.00 a $109,790.00	  </td>	</tr>
	<tr>				<td>	Fracción X No cumplir los requisitos de deducibilidad de donativos	  </td>	<td>		  </td>	<td>	De 3 a 5 veces el monto o valorseñalado en el comprobantefiscal que ampare el donativo	  </td>	<td>	De 3 a 5 veces el monto o valor señalado en el comprobante fiscal que ampare el donativo	  </td>	<td>	De 3 a 5 veces el monto o valor señalado en el comprobante fiscal que ampare el donativo	  </td>	</tr>
	<tr>				<td>	 Fracción XI No expedir o acompañar la documentación que ampare mercancías en transporte en territorio nacional	  </td>	<td>		  </td>	<td>	De $530.00 a $10,420.00	  </td>	<td>	De $530.00 a $10,420.00	  </td>	<td>	De $530.00 a $10,420.00	  </td>	</tr>
	<tr>				<td>	Fracción XIII No identificar en contabilidad las operaciones con partes relacionadas residentes en el extranjero	  </td>	<td>		  </td>	<td>	De $1,380.00 a $4,150.00 Por cada operación no identificada en contabilidad	  </td>	<td>	De $1,380.00 a $4,150.00 Por cada operación no identificada en contabilidad	  </td>	<td>	De $1,380.00 a $4,150.00 Por cada operación no identificada en contabilidad	  </td>	</tr>
	<tr>				<td>	Fracción XIV No dar a conocer a la Asamblea General de Accionistas un reporte en el que se informe sobre el cumplimiento de las obligaciones fiscales a su cargo en el corresponda el dictamenejercicio fiscal al que	  </td>	<td>		  </td>	<td>	De $25,470.00 a $38,200.00, cuando el reporte no sea presentado por el contribuyente, y de $9,430.00 a $18,860.00, cuando el reporte no sea presentado ante la asamblea de socios o accionistas	  </td>	<td>	De $25,470.00 a $38,200.00, cuando el reporte no sea presentado por el contribuyente, y de $9,430.00 a $18,860.00, cuando el reporte no sea presentado ante la asamblea de socios o accionistas	  </td>	<td>	No aplica	  </td>	</tr>
	<tr>				<td>	Fracción XV No presentar, o presentar de manera incompleta, la declaración informativa sobre la situación fiscal a que se refiere el artículo 32-H del CFF	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $10,980.00 a $109,790.00	  </td>	</tr>
	<tr>				<td>	Fracción XVI No demostrar la existencia de las operaciones amparadas por los comprobantes fiscales emitidos por sus proveedores, relacionados con el IVA	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $12,070.00 a $69,000.00	  </td>	</tr>
	<tr>	<td rowspan="13">	Artículo 84-B Multas por infracciones de instituciones de crédito	  </td>	<td>	Fracción I No anotar el nombre, denominación o razón social y la clave del primer titular de la cuenta, en los esqueletos para expedición de cheques	  </td>	<td>		  </td>	<td>	De $260.00 a $11,960.00	  </td>	<td>	De $260.00 a $11,960.00	  </td>	<td>	De $260.00 a $11,960.00	  </td>	</tr>
	<tr>				<td>	Fracción II Pagar en efectivo o abonar en cuenta distinta a la del beneficiario, un cheque que tenga inserta la expresión “para abono en cuenta”	  </td>	<td>		  </td>	<td>	20% del valor del cheque	  </td>	<td>	20% del valor del cheque	  </td>	<td>	20% del valor del cheque	  </td>	</tr>
	<tr>				<td>	Fracción III Procesar incorrectamente las declaraciones de pago de contribuciones	  </td>	<td>		  </td>	<td>	De $30.00 a $50.00 Por cada dato no asentado, o asentado incorrectamente	  </td>	<td>	De $30.00 a $60.00 Por cada dato no asentado, o asentado incorrectamente	  </td>	<td>	De $30.00 a $60.00 Por cada dato no asentado, o asentado incorrectamente	  </td>	</tr>
	<tr>				<td>	Fracción IV No proporcionar la información solicitada por las autoridades fiscales	  </td>	<td>		  </td>	<td>	De $397,070.00 a $794,140.00	  </td>	<td>	De $397,070.00 a $794,140.00	  </td>	<td>	De $397,070.00 a $794,140.00	  </td>	</tr>
	<tr>				<td>	 Fracción V Asentar incorrectamente o no asentar los datos del cuentahabiente	  </td>	<td>		  </td>	<td>	De $5,210.00 a $78,080.00	  </td>	<td>	De $5,210.00 a $78,080.00	  </td>	<td>	De $5,210.00 a $78,080.00	  </td>	</tr>
	<tr>				<td>	Fracción VI No transferir a la Tesorería de la Federación, el importe de la garantía y sus rendimientos	  </td>	<td>		  </td>	<td>	De $19,840.00 a $59,550.00	  </td>	<td>	De $19,840.00 a $59,550.00	  </td>	<td>	De $19,840.00 a $59,550.00	  </td>	</tr>
	<tr>				<td rowspan="2">	Fracción VII No expedir los estados de cuenta a que se refiere el artículo 32-B del CFF	  </td>	<td>		  </td>	<td>	De $70.00 a $140.00 Por cada estado de cuenta no emitido	  </td>	<td>	De $70.00 a $140.00 Por cada estado de cuenta no emitido	  </td>	<td>	De $70.00 a $140.00 Por cada estado de cuenta no emitido	  </td>	</tr>
	<tr>							<td>		  </td>	<td>	De $279,507.00 a $559,014.00 por no proporcionar la información	  </td>	<td>	De $279,507.00 a $559,014.00 por no proporcionar la información	  </td>	<td>	De $279,507.00 a $559,014.00 por no proporcionar la información	  </td>	</tr>
	<tr>				<td>	Fracción VIII Hasta el 31/dic/13, no realizar la inmovilización de depósitos a que se refiere el artículo 156-Bis del CFF. A partir del 1o./ene/14, no practicar el aseguramiento, embargo o inmovilización de los depósitos bancarios, otros depósitos o seguros, en los plazos a que se refieren los artículos 40-A, 145,151 y 156-Bis del CFF, o negar la información al contribuyente acerca de la autoridad que ordenó el aseguramiento, embargo o inmovilización; así como ejecutar el aseguramiento, embargo o inmovilización por una cantidad mayor a la ordenada por la autoridad fiscal	  </td>	<td>		  </td>	<td>	De $225,000.00 a $250,000.00	  </td>	<td>	De $253,030.00 a $281,150.00	  </td>	<td>	De $253,030.00 a $281,150.00	  </td>	</tr>
	<tr>				<td>	Fracción IX Hasta el 31/dic/13, no informar a la autoridad fiscal sobre la inmovilización de los depósitos a que se refiere el artículo 156-Bis del CFF, en el plazo señalado por dicha autoridad. A partir del 1o./ene/14, no informar a la autoridad fiscal sobre la práctica o levantamiento del aseguramiento, embargo o inmovilización de los depósitos bancarios, otros depósitos o seguros, conforme a lo previsto en los artículos 40-A, 145, 151 y 156-Bis del CFF.	  </td>	<td>		  </td>	<td>	De $225,000.00 a $250,000.00	  </td>	<td>	De $253,030.00 a $281,150.00	  </td>	<td>	De $253,030.00 a $281,150.00	  </td>	</tr>
	<tr>				<td>	Fracción X No proporcionen las entidades financieras o sociedades cooperativas de ahorro y préstamo la información contenida en los estados de cuenta del contribuyente, cuando la autoridad fiscal así lo solicite.	  </td>	<td>		  </td>	<td>	De $50,000.00 a $60,000.00	  </td>	<td>	De $50,000.00 a $60,000.00	  </td>	<td>	De $50,000.00 a $60,000.00	  </td>	</tr>
	<tr>				<td>	Fracción XI No levantar el aseguramiento, embargo o inmovilización de los depósitos bancarios, otros depósitos o seguros del contribuyente, conforme a lo previsto en los artículos 40-A, 145, 151 y 156-Bis del CFF	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $225,000.00 a $500,000.00	  </td>	</tr>
	<tr>				<td>	Fracción XII No validar con el SAT que sus cuentahabientes se encuentren inscritos en el RFC y que su clave sea correcta	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $4,650.00 a $69,650.00	  </td>	</tr>
	<tr>	<td>	Artículo 84-D Multas a usuarios de servicios y cuenta- habientes de institucionesde crédito	  </td>	<td>	No proporcionar información o hacerlo incorrecta o falsamente, por cada omisión	  </td>	<td>		  </td>	<td>	De $340.00 y de $1,010.00 En el caso de usuarios del sistema financiero	  </td>	<td>	De $340.00 y de $1,010.00 En el caso de usuarios del sistema financiero	  </td>	<td>	De $340.00 y de $1,010.00 En el caso de usuarios del sistema financiero	  </td>	</tr>
	<tr>	<td>	Artículo 84-F	  </td>	<td>	No efectuar la notificación de la cesión de créditos de empresas de factoraje financiero	  </td>	<td>		  </td>	<td>	De $5,210.00 a $52,060.00	  </td>	<td>	De $5,210.00 a $52,060.00	  </td>	<td>	De $5,210.00 a $52,060.00	  </td>	</tr>
	<tr>	<td>	Artículo 84-H Multas relacionadas con infracciones cometidas por casas de bolsa	  </td>	<td>	No proporcionen las casas de bolsa, la información a que se refiere el artículo 60 de la Ley del ISR, respecto de contribuyentes que enajenen acciones con su intermediación.	  </td>	<td>		  </td>	<td>	De $3,700.00 a $7,410.00 Por cada informe no proporcionado	  </td>	<td>	De $4,160.00 a $8,330.00  proporcionado	  </td>	<td>	De $4,160.00 a $8,330.00 Por cada informe no proporcionado	  </td>	</tr>
	<tr>	<td>	Artículo 84-J Multas relacionadas con las personas morales autorizadas para emitir tarjetas de crédito, de débito o de servicio o monederos electrónicos	  </td>	<td>	No expidan las personas morales autorizadas para emitir tarjetas de crédito, de débito o de servicio o monederos electrónicos, en relación con las obligaciones a que se refiere el artículo 32-E del CFF, los estados de cuenta en términos del artículo 29-C del CFF.	  </td>	<td>		  </td>	<td>	De $70.00 a $140.00 Por cada estado de cuenta no emitido en términos del artículo 32-E del CFF	  </td>	<td>	De $70.00 a $140.00 Por cada estado de cuenta no emitido en términos del artículo 32-E del CFF	  </td>	<td>	De $70.00 a $140.00 Por cada estado de cuenta no emitido en términos del artículo 32-E del CFF	  </td>	</tr>
	<tr>	<td>	Artículo 84-L Multas relacionadas con las personas morales autorizadas para emitir tarjetas de crédito, de débito o de servicio o monederos electrónicos	  </td>	<td>	No proporcionen al SAT las personas morales autorizadas para emitir tarjetas de crédito, de débito o de servicio o monederos electrónicos la información contenida en los estados de cuenta, a que se refiere el artículo 32-E del CFF.	  </td>	<td>		  </td>	<td>	De $279,507.00 a $559,014.00	  </td>	<td>	De $279,507.00 a $559,014.00	  </td>	<td>	De $279,507.00 a $559,014.00	  </td>	</tr>
	<tr>	<td rowspan="5">	Artículo 86 Multas relacionadas con el ejercicio de facultades de comprobación	  </td>	<td>	Fracción I Oponerse a que se practique visita en el domicilio fiscal. No proporcionar los datos e informes, la contabilidad o los elementos que exijan las autoridades fiscales	  </td>	<td>		  </td>	<td>	De $13,720.00 a $41,170.00	  </td>	<td>	De $13,720.00 a $41,170.00	  </td>	<td>	De $13,720.00 a $41,170.00	  </td>	</tr>
	<tr>				<td>	Fracción II No conservar la contabilidad o la correspondencia que los visitadores dejen en depósito	  </td>	<td>		  </td>	<td>	De $1,200.00 a $49,550.00	  </td>	<td>	De $1,200.00 a $49,550.00	  </td>	<td>	De $1,200.00 a $49,550.00	  </td>	</tr>
	<tr>				<td>	Fracción III No proporcionar información de clientes y proveedores que soliciten las autoridades fiscales	  </td>	<td>		  </td>	<td>	De $2,600.00 a $65,080.00	  </td>	<td>	De $2,600.00 a $65,080.00	  </td>	<td>	De $2,600.00 a $65,080.00	  </td>	</tr>
	<tr>				<td>	Fracción IV Divulgar, hacer uso personal o indebido, de información confidencial proporcionada por terceros independientes que afecte su posición competitiva	  </td>	<td>		  </td>	<td>	De $104,890.00 a $139,850.00	  </td>	<td>	De $104,890.00 a $139,850.00	  </td>	<td>	De $104,890.00 a $139,850.00	  </td>	</tr>
	<tr>				<td>	Fracción V Declarar falsamente que se cumplen los requisitos para tener derecho a la reducción de multas, y aplicación de recargos por prórroga	  </td>	<td>		  </td>	<td>	De $5,950.00 a $9,920.00	  </td>	<td>	De $5,950.00 a $9,920.00	  </td>	<td>	De $5,950.00 a $9,920.00	  </td>	</tr>
	<tr>	<td rowspan="5">	 Artículo 86-B Multas relacionadas con la omisión de colocar marbetes	  </td>	<td>	Fracción I Hasta el 31/dic/13, no adherir marbetes o precintos en los envases o recipientes que contengan bebidas alcohólicas. A partir del 1o./ ene/14, no adherir marbetes o precintos a los envases o recipientes que contengan bebidas alcohólicas o que éstos sean falsos o se encuentren alterados	  </td>	<td>		  </td>	<td>	De $20.00 a $70.00 Por cada marbete o precinto	  </td>	<td>	De $20.00 a $70.00 Por cada marbete o precinto	  </td>	<td>	De $50.00 a $100.00 Por cada marbete o precinto	  </td>	</tr>
	<tr>				<td>	Fracción II Hacer uso diferente de los marbetes o precintos de los envases o recipientes de bebidas alcohólicas	  </td>	<td>		  </td>	<td>	De $30.00 a $100.00 Por cada marbete o precinto	  </td>	<td>	De $30.00 a $100.00 Por cada marbete o precinto	  </td>	<td>	De $30.00 a $100.00 Por cada marbete o precinto	  </td>	</tr>
	<tr>				<td>	Fracción III Hasta el 31/dic/13, poseer bebidas alcohólicas cuyos envases o recipientes carezcan del marbete o precinto correspondiente, o no cerciorarse que los adquiridos lo contengan. A partir del 1o./ene/14, poseer bebidas alcohólicas cuyos envases o recipientes carezcan del marbete o precinto correspondiente, o bien, que éstos sean falsos o se encuentren alterados, así como no cerciorarse que los adquiridos lo contengan	  </td>	<td>		  </td>	<td>	De $20.00 a $60.00 Por cada envase o recipiente	  </td>	<td>	De $20.00 a $60.00 Por cada envase o recipiente	  </td>	<td>	De $20.00 a $50.00 Por cada envase o recipiente	  </td>	</tr>
	<tr>				<td>	Fracción IV No destruir los envases vacíos que contenían bebidas alcohólicas cuando se esté obligado a ello	  </td>	<td>		  </td>	<td>	De $30.00 a $90.00  Por cada envase vacío no destruido 	  </td>	<td>	De $30.00 a $90.00 Por cada envase vacío no destruido 	  </td>	<td>	De $30.00 a $90.00 Por cada envase vacío no destruido	  </td>	</tr>
	<tr>				<td>	Fracción V No acreditar que los marbetes o precintos fueron adquiridos legalmente	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $400.00 a $600.00 Por cada marbete o precinto	  </td>	</tr>
	<tr>	<td>	Artículo 86-F Multas relacionadas con la obligación de llevar control físico de bebidas alcohólicas y tabacos labrados	  </td>	<td>	No llevar controles físicos o volumétricos, o llevarlos en forma distinta	  </td>	<td>		  </td>	<td>	De $38,890.00 a $90,750.00	  </td>	<td>	De $38,890.00 a $90,750.00	  </td>	<td>	De $38,890.00 a $90,750.00	  </td>	</tr>
	<tr>	<td rowspan="3">	Artículo 86-H Multas relacionadas con los productores, fabricantes e importadores de cigarros y otros tabacos labrados	  </td>	<td>	No imprimir el código de seguridad en cada una de las cajetillas de cigarros para su venta en México	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $10.00 a $20.00 Por cada cajetilla En caso de reincidencia la autoridad podrá clausurar el establecimiento por 15 días	  </td>	</tr>
	<tr>				<td>	No proporcionar o no poner a disposición de las autoridades fiscales la información, documentación o dispositivos que permitan constatar el cumplimiento las obligaciones señaladas en los artículos 19, fracción XXI y 19-A de La Ley del IEPS.	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $20,000.00 a $300,000.00 En caso de reincidencia, la autoridad podrá clausurar el establecimiento por 15 días	  </td>	</tr>
	<tr>				<td>	No permitir a las autoridades fiscales la realización de las verificaciones en los establecimientos en donde se encuentren los mecanismos o sistemas de impresión del código de seguridad en las cajetillas de cigarros	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $20,000.00 a $300,000.00 En caso de reincidencia, la autoridad podrá clausurar el establecimiento por 15 días	  </td>	</tr>
	<tr>	<td>	Artículo 86-J Multas relacionadas con el almacenamiento, enajenación o distribución de cajetillas de cigarros y otros tabacos labrados en México	  </td>	<td>	Almacenar, vender, enajenar o distribuir en México cajetillas de cigarros y otros tabacos labrados, que no contengan el código de seguridad previsto en el artículo 19, fracción XXII de la Ley del IEPS.	  </td>	<td>		  </td>	<td>	No aplica	  </td>	<td>	No aplica	  </td>	<td>	De $10.00 a $20.00 Por cada cajetilla	  </td>	</tr>
	<tr>	<td>	Artículo 88 Multas relacionadas con infracciones cometidas por ser vidores públicos	  </td>	<td>	No exigir el pago total de las contribuciones y sus accesorios; recaudar, permitir y ordenar que se reciba el pago en forma diversa, a la prevista en las disposiciones fiscales. Asentar datos falsos o exigir prestaciones no previstas en las disposiciones fiscales, o que se hayan practicado visitas en el domicilio fiscal o incluir en las actas relativas datos falsos; divulgar, hacer uso personal o indebido de información confidencial, proporcionada por terceros independientes. Revelar a terceros la información que las instituciones que componen el sistema financiero hayan proporcionado a las autoridades fiscales	  </td>	<td>		  </td>	<td>	De $104,890.00 a $139,850.00	  </td>	<td>	De $104,890.00 a $139,850.00	  </td>	<td>	De $104,890.00 a $139,850.00	  </td>	</tr>
	<tr>	<td>	Artículo 90 Multas relacionadas con infracciones cometidas por terceros	  </td>	<td>	Asesorar, aconsejar o prestar servicios para omitir total o parcialmente el pago de alguna contribución en contravención a las disposicontribución en contravención a las disposiciones fiscales.Colaborar en la alteración o la inscripción de cuentas, asientos o datos falsos en la contabilidad o en los documentos que se expidan.Ser cómplice en cualquier forma no prevista, en la comisión de infracciones fiscales.	  </td>	<td>		  </td>	<td>	De $39,670.00 a $62,340.00	  </td>	<td>	De $44,610.00 a $70,110.00	  </td>	<td>	De $44,610.00 a $70,110.00	  </td>	</tr>
	<tr>	<td>	Artículo 91 Cualquier infracción distinta de la señalada en el Capítulo I, del Título IV del CFF	  </td>	<td>		  </td>	<td>		  </td>	<td>	De $260.00 a $2,510.00	  </td>	<td>	De $260.00 a $2,510.00	  </td>	<td>	De $260.00 a $2,510.00	  </td>	</tr>
	<tr>	<td>	 Artículo 91-B Infracciones relaciondas con el dictamen de estados financieros, elaborado por contador público	  </td>	<td>	No observar la omisión de contribuciones recaudadas, retenidas, trasladadas o propias del contribuyente, en el informe sobre su situación fiscal, cuando las autoridades fiscales determinen tal omisión, mediante resolución que quede firme. No aplica esta infracción, cuando dicha omisión no supere el 20% de las contribuciones recaudadas, retenidas o trasladadas, o el 30% de las contribuciones propias del contribuyente	  </td>	<td>		  </td>	<td>	 cobrados por la elaboración delDe 10 a 20% de las contribuciones omitidas, sin exceder del doble de los honorarios dictamen	  </td>	<td>	De 10 a 20% de las contribuciones omitidas, sin exceder del doble de los honorarios cobrados por la elaboración del dictamen	  </td>	<td>	De 10 a 20% de las contribuciones omitidas, sin exceder del doble de los honorarios cobrados por la elaboración del dictamen	  </td>	</tr>

</tbody>
	  <!-- ******* -->
            </table>
          </div>

      </div>
    </div>
</div>
@stop

@section('javascript')
<script>
$('#ulIFe').addClass('in');
$('#liCantidadesCFF').addClass('activoBorde');
</script>
@stop
