<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="author" content="edSantiago" />
  <link rel="icon" type="../../../../image/png" href="./favicon.png"/>

  <title>

    Indicadores Fiscales | Vázquez Hernández Contadores, S. C.
  </title>

  <link href="../../../../css/bootstrap.min.css" rel="stylesheet">
  <link href="../../../../fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet">

  <link href="../../../../css/publicos/pagina.css" rel="stylesheet">
</head>


  <body>
      <?php include ("../../../../seccionesVista/barraNavegacionPagina.php"); ?>


        <div class="fondoInfoteca fondo paddingMenu">
            <div class="row">
              <div class="col-lg-12">
                <br>
                <h1 class="tamTitulo grisClaro texto3D tituloEntrada">
                  <i class="fa fa-line-chart"></i> Indicadores</h1>
                <br>
              </div>
            </div>

            <div class="row">

             <div class="col-md-2 transladarIzquierda">
                    <?php include ("../../../../seccionesVista/menuIndicadoresF.php"); ?>   <!-- MUESTRA MENU DE ARTICULOS menuArticulo.blde.php -->
              </div>

              <div class="col-md-10 animacionContenido">
  <!--  -->      <!-- MUESTRA EL CONTENIDO DEL ARTICULO -->
  <div class="well transparenteClaroTxt">
  <div class="row">
    <div class="col-md-12">
     <div class="table-responsive">
            <table class="table table-striped  table-bordered table-condensed">
          <!-- ******** -->
          <h3 class="text-center">	Tasa de interés interbancario de equilibrio (T.I.I.E.) 2016	</h3>
          <thead>
          	<tr  class="activoLiMenu">	<th rowspan="2" class="text-center">	publicación en el D.O.F	</th>	<th colspan="2" class="text-center">	Enero	</th>				<th colspan="2" class="text-center">	Febrero	</th>				<th colspan="2" class="text-center">	Marzo	</th>				<th colspan="2" class="text-center">	Abril	</th>				<th colspan="2" class="text-center">	Mayo	</th>				<th colspan="2" class="text-center">	Junio	</th>				<th colspan="2" class="text-center">	Julio	</th>				<th colspan="2" class="text-center">	Agosto	</th>				<th colspan="2" class="text-center">	Septiembre	</th>				<th colspan="2" class="text-center">	Octubre	</th>				<th colspan="2" class="text-center">	Noviembre	</th>				<th colspan="2" class="text-center">	Diciembre	</th>				</tr>
          	<tr  class="activoLiMenu">				<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días	</th>	<th  class="text-center">	91 días	</th>	</tr>
          </thead>
          <tbody class="animEscalarFila">
            <tr>	<td  class="text-center">	1	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.0594	  </td>	<td  class="text-center">	4.0944	</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.115900	</td>	<td  class="text-center">	4.100000	  </td>	<td  class="text-center">	4.202500	  </td>	<td  class="text-center">	4.113800	  </td>	<td  class="text-center">	4.232000	  </td>	<td  class="text-center">	4.585	  </td>	<td  class="text-center">	4.685	  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.6725	  </td>																			</tr>
          	<tr>	<td  class="text-center">	2	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3.557	  </td>	<td  class="text-center">	3.5904	  </td>	<td  class="text-center">	4.0577	  </td>	<td  class="text-center">	4.09	</td>	<td  class="text-center">	4.062500	  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.065500	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center">	4.095800	  </td>	<td  class="text-center">	4.199900	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.585	  </td>	<td  class="text-center">	4.685	  </td>	<td  class="text-center">	4.5925	  </td>	<td  class="text-center">	4.6775	  </td>																			</tr>
          	<tr>	<td  class="text-center">	3	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3.5550	  </td>	<td  class="text-center">	3.5912	  </td>	<td  class="text-center">	4.06	  </td>	<td  class="text-center">	4.1044	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center">	4.096500	  </td>	<td  class="text-center">	4.193500	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.5836	  </td>	<td  class="text-center">	4.6846	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>
          	<tr>	<td  class="text-center">	4	  </td>	<td  class="text-center">	3.555	  </td>	<td  class="text-center">	3.5886	  </td>	<td  class="text-center">	3.5588	  </td>	<td  class="text-center">	3.5916	  </td>	<td  class="text-center">	4.0601	  </td>	<td  class="text-center">	4.1075	</td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center">	4.062500	  </td>	<td  class="text-center">	4.114000	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.560000	  </td>	<td  class="text-center">	4.645000	  </td>	<td  class="text-center">	4.5828	  </td>	<td  class="text-center">	4.6843	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>
          	<tr>	<td  class="text-center">	5	  </td>	<td  class="text-center">	3.5575	  </td>	<td  class="text-center">	3.5866	  </td>	<td  class="text-center">	3.56	  </td>	<td  class="text-center">	3.5925	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center">	4.063300	  </td>	<td  class="text-center">	4.114800	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.560500	  </td>	<td  class="text-center">	4.660000	  </td>	<td  class="text-center">	4.5874	  </td>	<td  class="text-center">	4.6894	  </td>	<td  class="text-center">	4.5925	  </td>	<td  class="text-center">	4.6725	  </td>																			</tr>
          	<tr>	<td  class="text-center">	6	  </td>	<td  class="text-center">	3.5540	  </td>	<td  class="text-center">	3.5785	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.065300	  </td>	<td  class="text-center">	4.116400	</td>	<td  class="text-center">	4.063800	  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.092600	  </td>	<td  class="text-center">	4.190000	  </td>	<td  class="text-center">	4.571500	  </td>	<td  class="text-center">	4.670000	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.685	  </td>																			</tr>
          	<tr>	<td  class="text-center">	7	  </td>	<td  class="text-center">	3.56	  </td>	<td  class="text-center">	3.5892	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.064	  </td>	<td  class="text-center">	4.11	</td>	<td  class="text-center">	4.066100	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.091500	  </td>	<td  class="text-center">	4.183600	  </td>	<td  class="text-center">	4.577500	  </td>	<td  class="text-center">	4.675000	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.6875	  </td>																			</tr>
          	<tr>	<td  class="text-center">	8	  </td>	<td  class="text-center">	3.56	  </td>	<td  class="text-center">	3.59	  </td>	<td  class="text-center">	3.5616	  </td>	<td  class="text-center">	3.5921	  </td>	<td  class="text-center">	4.0625	  </td>	<td  class="text-center">	4.1085	</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">	4.115000	</td>	<td  class="text-center">	4.088600	  </td>	<td  class="text-center">	4.189000	  </td>	<td  class="text-center">	4.582100	  </td>	<td  class="text-center">	4.677600	  </td>	<td  class="text-center">	4.586	  </td>	<td  class="text-center">	4.688	  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.6888	  </td>																			</tr>
          	<tr>	<td  class="text-center">	9	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3.5580	  </td>	<td  class="text-center">	3.5881	  </td>	<td  class="text-center">	4.0606	  </td>	<td  class="text-center">	4.1121	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.114600	</td>	<td  class="text-center">	4.092500	  </td>	<td  class="text-center">	4.197500	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.5906	  </td>	<td  class="text-center">	4.6908	  </td>	<td  class="text-center">	4.59	  </td>	<td  class="text-center">	4.685	  </td>																			</tr>
          	<tr>	<td  class="text-center">	10	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3.5598	  </td>	<td  class="text-center">	3.59	  </td>	<td  class="text-center">	4.0601	  </td>	<td  class="text-center">	4.1135	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.061100	  </td>	<td  class="text-center">	4.114100	</td>	<td  class="text-center">	4.086900	  </td>	<td  class="text-center">	4.185600	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.59	  </td>	<td  class="text-center">	4.69	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>
          	<tr>	<td  class="text-center">	11	  </td>	<td  class="text-center">	3.5545	  </td>	<td  class="text-center">	3.5821	  </td>	<td  class="text-center">	3.5541	  </td>	<td  class="text-center">	3.5873	  </td>	<td  class="text-center">	4.0606	  </td>	<td  class="text-center">	4.1117	</td>	<td  class="text-center">	4.062400	  </td>	<td  class="text-center">	4.116100	</td>	<td  class="text-center">	4.059900	  </td>	<td  class="text-center">	4.113900	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.576000	  </td>	<td  class="text-center">	4.668800	  </td>	<td  class="text-center">	4.59	  </td>	<td  class="text-center">	4.69	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>
          	<tr>	<td  class="text-center">	12	  </td>	<td  class="text-center">	3.5539	  </td>	<td  class="text-center">	3.5856	  </td>	<td  class="text-center">	3.5550	  </td>	<td  class="text-center">	3,585.0000	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.062500	  </td>	<td  class="text-center">	4.113000	</td>	<td  class="text-center">	4.060300	  </td>	<td  class="text-center">	4.113900	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.575800	  </td>	<td  class="text-center">	4.675800	  </td>	<td  class="text-center">	4.5875	  </td>	<td  class="text-center">	4.6875	  </td>	<td  class="text-center">	4.5906	  </td>	<td  class="text-center">	4.6835	  </td>																			</tr>
          	<tr>	<td  class="text-center">	13	  </td>	<td  class="text-center">	3.5505	  </td>	<td  class="text-center">	3.5839	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.062500	  </td>	<td  class="text-center">	4.112500	</td>	<td  class="text-center">	4.060700	  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.095000	  </td>	<td  class="text-center">	4.201600	  </td>	<td  class="text-center">	4.580600	  </td>	<td  class="text-center">	4.680800	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.591	  </td>	<td  class="text-center">	4.6823	  </td>																			</tr>
          	<tr>	<td  class="text-center">	14	  </td>	<td  class="text-center">	3.5579	  </td>	<td  class="text-center">	3.59	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.0613	  </td>	<td  class="text-center">	4.1199	</td>	<td  class="text-center">	4.061800	  </td>	<td  class="text-center">	4.112500	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.098600	  </td>	<td  class="text-center">	4.196800	  </td>	<td  class="text-center">	4.585000	  </td>	<td  class="text-center">	4.685000	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.69	  </td>																			</tr>
          	<tr>	<td  class="text-center">	15	  </td>	<td  class="text-center">	3.5543	  </td>	<td  class="text-center">	3.5865	  </td>	<td  class="text-center">	3.5476	  </td>	<td  class="text-center">	3.5813	  </td>	<td  class="text-center">	4.0625	  </td>	<td  class="text-center">	4.115	</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center">	4.110000	  </td>	<td  class="text-center">	4.215000	  </td>	<td  class="text-center">	4.589000	  </td>	<td  class="text-center">	4.689500	  </td>	<td  class="text-center">	4.5916	  </td>	<td  class="text-center">	4.6918	  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.69	  </td>																			</tr>
          	<tr>	<td  class="text-center">	16	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3.5483	  </td>	<td  class="text-center">	3.5825	  </td>	<td  class="text-center">	4.0645	  </td>	<td  class="text-center">	4.12	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center">	4.103700	  </td>	<td  class="text-center">	4.207100	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.5912	  </td>	<td  class="text-center">	4.6923	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>
          	<tr>	<td  class="text-center">	17	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3.5543	  </td>	<td  class="text-center">	3.5858	  </td>	<td  class="text-center">	4.0647	  </td>	<td  class="text-center">	4.115	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.066000	  </td>	<td  class="text-center">	4.115500	</td>	<td  class="text-center">	4.104600	  </td>	<td  class="text-center">	4.199100	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.5911	  </td>	<td  class="text-center">	4.692	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>
          	<tr>	<td  class="text-center">	18	  </td>	<td  class="text-center">	3.5547	  </td>	<td  class="text-center">	3.5875	  </td>	<td  class="text-center">	4.0350	  </td>	<td  class="text-center">	4.0425	  </td>	<td  class="text-center">	4.0648	  </td>	<td  class="text-center">	4.115	</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.117500	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.590000	  </td>	<td  class="text-center">	4.690000	  </td>	<td  class="text-center">	4.5937	  </td>	<td  class="text-center">	4.6946	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>
          	<tr>	<td  class="text-center">	19	  </td>	<td  class="text-center">	3.5598	  </td>	<td  class="text-center">	3.59	  </td>	<td  class="text-center">	4.0303	  </td>	<td  class="text-center">	4.0578	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.065200	  </td>	<td  class="text-center">	4.115800	</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.137500	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.590000	  </td>	<td  class="text-center">	4.690000	  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.695	  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.69	  </td>																			</tr>
          	<tr>	<td  class="text-center">	20	  </td>	<td  class="text-center">	3.5551	  </td>	<td  class="text-center">	3.5886	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.062600	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center">	4.081200	  </td>	<td  class="text-center success">		</td>	<td  class="text-center ">	4.105000	  </td>	<td  class="text-center ">	4.200100	  </td>	<td  class="text-center">	4.587500	  </td>	<td  class="text-center">	4.687000	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.5951	  </td>	<td  class="text-center">	4.714	  </td>																			</tr>
          	<tr>	<td  class="text-center">	21	  </td>	<td  class="text-center">	3,554.0000	  </td>	<td  class="text-center">	3.5871	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.109100	  </td>	<td  class="text-center">	4.213800	  </td>	<td  class="text-center">	4.590800	  </td>	<td  class="text-center">	4.690600	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.625	  </td>	<td  class="text-center">	4.74	  </td>																			</tr>
          	<tr>	<td  class="text-center">	22	  </td>	<td  class="text-center">	3.56	  </td>	<td  class="text-center">	3.5925	  </td>	<td  class="text-center">	4035	  </td>	<td  class="text-center">	4055	  </td>	<td  class="text-center">	4.066	  </td>	<td  class="text-center">	4.115	</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.132800	</td>	<td  class="text-center">	4.110000	  </td>	<td  class="text-center">	4.219500	  </td>	<td  class="text-center">	4.585400	  </td>	<td  class="text-center">	4.685300	  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.6955	  </td>	<td  class="text-center">	4.6275	  </td>	<td  class="text-center">	4.755	  </td>																			</tr>
          	<tr>	<td  class="text-center">	23	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.0316	  </td>	<td  class="text-center">	4.0516	  </td>	<td  class="text-center">	4.065	  </td>	<td  class="text-center">	4.115	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.077500	  </td>	<td  class="text-center">	4.157800	</td>	<td  class="text-center">	4.099500	  </td>	<td  class="text-center">	4.210800	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.594	  </td>	<td  class="text-center">	4.693	  </td>	<td  class="text-center">	4.6343	  </td>	<td  class="text-center">	4.7554	  </td>																			</tr>
          	<tr>	<td  class="text-center">	24	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.0507	  </td>	<td  class="text-center">	4.08	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.093600	  </td>	<td  class="text-center">	4.181700	</td>	<td  class="text-center">	4.099500	  </td>	<td  class="text-center">	4.209800	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.6949	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>
          	<tr>	<td  class="text-center">	25	  </td>	<td  class="text-center">	3.5545	  </td>	<td  class="text-center">	3.5886	  </td>	<td  class="text-center">	4.0547	  </td>	<td  class="text-center">	4.0825	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.062500	  </td>	<td  class="text-center">	4.112500	</td>	<td  class="text-center">	4.108100	  </td>	<td  class="text-center">	4.189500	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.584900	  </td>	<td  class="text-center">	4.684600	  </td>	<td  class="text-center">	4.5925	  </td>	<td  class="text-center">	4.6925	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>
          	<tr>	<td  class="text-center">	26	  </td>	<td  class="text-center">	3.56	  </td>	<td  class="text-center">	3.59	  </td>	<td  class="text-center">	4.0555	  </td>	<td  class="text-center">	4.09	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center">	4.112500	  </td>	<td  class="text-center">	4.182500	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.589500	  </td>	<td  class="text-center">	4.689200	  </td>	<td  class="text-center">	4.5925	  </td>	<td  class="text-center">	4.6925	  </td>	<td  class="text-center">	4.6389	  </td>	<td  class="text-center">	4.7575	  </td>																			</tr>
          	<tr>	<td  class="text-center">	27	  </td>	<td  class="text-center">	3.5610	  </td>	<td  class="text-center">	3.5917	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.065500	  </td>	<td  class="text-center">	4.115900	</td>	<td  class="text-center">	4.095000	  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.104200	  </td>	<td  class="text-center">	4.212000	  </td>	<td  class="text-center">	4.590000	  </td>	<td  class="text-center">	4.690000	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.6369	  </td>	<td  class="text-center">	4.7562	  </td>																			</tr>
          	<tr>	<td  class="text-center">	28	  </td>	<td  class="text-center">	3.56	  </td>	<td  class="text-center">	3.5915	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.0674	  </td>	<td  class="text-center">	4.115	</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.118500	  </td>	<td  class="text-center">	4.237300	  </td>	<td  class="text-center">	4.588200	  </td>	<td  class="text-center">	4.687500	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.6399	  </td>	<td  class="text-center">	4.76	  </td>																			</tr>
          	<tr>	<td  class="text-center">	29	  </td>	<td  class="text-center">	3.5551	  </td>	<td  class="text-center">	3.5882	  </td>	<td  class="text-center">	4.0501	  </td>	<td  class="text-center">	4.08	  </td>	<td  class="text-center">	4.065	  </td>	<td  class="text-center">	4.115	</td>	<td  class="text-center">	4.065000	  </td>	<td  class="text-center">	4.115000	</td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.184800	</td>	<td  class="text-center">	4.113100	  </td>	<td  class="text-center">	4.231000	  </td>	<td  class="text-center">	4.587400	  </td>	<td  class="text-center">	4.687500	  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.695	  </td>	<td  class="text-center">	4.6439	  </td>	<td  class="text-center">	4.7805	  </td>																			</tr>
          	<tr>	<td  class="text-center">	30	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.0625	  </td>	<td  class="text-center">	4.1125	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.097500	  </td>	<td  class="text-center">	4.191500	</td>	<td  class="text-center">	4.111600	  </td>	<td  class="text-center">	4.222500	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.695	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>
          	<tr>	<td  class="text-center">	31	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.065	  </td>	<td  class="text-center">	4.115	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	4.097000	  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	4.595	  </td>	<td  class="text-center">	4.6475	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>																			</tr>






      </tbody>



          <!-- *********** -->
                </table>
              </div>
            </div>
        </div>
      </div>

<div class="well transparenteClaroTxt">
  <div class="row">
    <div class="col-md-12">
     <div class="table-responsive">
            <table class="table table-striped  table-bordered table-condensed">
          <!-- ******** -->
          <h3 class="text-center">	Tasa de interés interbancario de equilibrio (T.I.I.E.) 2015	</h3>

          <thead>
            <tr  class="activoLiMenu">	<th rowspan="2" class="text-center">	publicación en el D.O.F	</th>	<th colspan="2" class="text-center">	enero 	</th>				<th colspan="2" class="text-center">	febrero 	</th>				<th colspan="2" class="text-center">	marzo 	</th>				<th colspan="2" class="text-center">	abril 	</th>				<th colspan="2" class="text-center">	mayo 	</th>				<th colspan="2" class="text-center">	junio 	</th>				<th colspan="2" class="text-center">	julio 	</th>				<th colspan="2" class="text-center">	agosto 	</th>				<th colspan="2" class="text-center">	septiembre 	</th>				<th colspan="2" class="text-center">	octubre 	</th>					<th colspan="2" class="text-center">	noviembre 	</th>				<th colspan="2" class="text-center">	diciembre	</th>			</tr>
          	<tr  class="activoLiMenu">				<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	</tr>
          </thead>
          <tbody class="animEscalarFila">
          	<tr>	<td  class="text-center">	1	  </td>	<td  class="text-center">	3,3205	  </td>	<td  class="text-center">	3,3245	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.299	  </td>	<td  class="text-center">	3.3262	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.32	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.335	  </td>	<td  class="text-center">	3.3575	</td>	<td  class="text-center">	3.3225	  </td>	<td  class="text-center">	3.3348	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3116	  </td>	<td  class="text-center">	3.4035	</td>	</tr>
          	<tr>	<td  class="text-center">	2	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3.2987	  </td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3089	  </td>	<td  class="text-center">	3.3197	</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.335	  </td>	<td  class="text-center">	3.3648	</td>	<td  class="text-center">	3.3247	  </td>	<td  class="text-center">	3.34	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.325	  </td>	<td  class="text-center">	3.415	</td>	</tr>
          	<tr>	<td  class="text-center">	3	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3,2950	  </td>	<td  class="text-center">	3,3030	  </td>	<td  class="text-center">	3.29	  </td>	<td  class="text-center">	3.3	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3075	  </td>	<td  class="text-center">	3.315	</td>	<td  class="text-center">	3.3037	  </td>	<td  class="text-center">	3.3104	</td>	<td  class="text-center">	3.33	  </td>	<td  class="text-center">	3.33	</td>	<td  class="text-center">	3.3358	  </td>	<td  class="text-center">	3.363	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.325	</td>	<td  class="text-center">	3.3358	  </td>	<td  class="text-center">	3.4321	</td>	</tr>
          	<tr>	<td  class="text-center">	4	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3,3010	  </td>	<td  class="text-center">	3,3005	  </td>	<td  class="text-center">	3.2934	  </td>	<td  class="text-center">	3.3067	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3062	  </td>	<td  class="text-center">	3.312	</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3513	  </td>	<td  class="text-center">	3.3513	</td>	<td  class="text-center">	3.335	  </td>	<td  class="text-center">	3.3643	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.3225	</td>	<td  class="text-center">	3.34	  </td>	<td  class="text-center">	3.44	</td>	</tr>
          	<tr>	<td  class="text-center">	5	  </td>	<td  class="text-center">	3,3240	  </td>	<td  class="text-center">	3,3290	  </td>	<td  class="text-center">	3,3000	  </td>	<td  class="text-center">	3,3100	  </td>	<td  class="text-center">	3.2953	  </td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.32	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.352	  </td>	<td  class="text-center">	3.352	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3125	  </td>	<td  class="text-center">	3.325	</td>	<td  class="text-center">	3.3005	  </td>	<td  class="text-center">	3.335	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	</tr>
          	<tr>	<td  class="text-center">	6	  </td>	<td  class="text-center">	3,3225	  </td>	<td  class="text-center">	3,3300	  </td>	<td  class="text-center">	3,2925	  </td>	<td  class="text-center">	3,3000	  </td>	<td  class="text-center">	3.2875	  </td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center">	3.295	  </td>	<td  class="text-center">	3.3225	</td>	<td  class="text-center">	3.295	  </td>	<td  class="text-center">	3.305	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center">	3.3466	  </td>	<td  class="text-center">	3.3466	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.33	</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.3315	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	</tr>
          	<tr>	<td  class="text-center">	7	  </td>	<td  class="text-center">	3,3050	  </td>	<td  class="text-center">	3,3150	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.32	</td>	<td  class="text-center">	3.3075	  </td>	<td  class="text-center">	3.3175	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2988	  </td>	<td  class="text-center">	3.3116	</td>	<td  class="text-center">	3.345	  </td>	<td  class="text-center">	3.345	</td>	<td  class="text-center">	3.334	  </td>	<td  class="text-center">	3.364	</td>	<td  class="text-center">	3.3134	  </td>	<td  class="text-center">	3.331	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.33	  </td>	<td  class="text-center">	3.435	</td>	</tr>
          	<tr>	<td  class="text-center">	8	  </td>	<td  class="text-center">	3,3000	  </td>	<td  class="text-center">	3,3100	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.29	  </td>	<td  class="text-center">	3.3115	</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.3105	  </td>	<td  class="text-center">	3.32	</td>	<td  class="text-center">	3.2925	  </td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.339	  </td>	<td  class="text-center">	3.37	</td>	<td  class="text-center">	3.305	  </td>	<td  class="text-center">	3.3212	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.34	  </td>	<td  class="text-center">	3.4425	</td>	</tr>
          	<tr>	<td  class="text-center">	9	  </td>	<td  class="text-center">	3,3075	  </td>	<td  class="text-center">	3,3135	  </td>	<td  class="text-center">	3,2910	  </td>	<td  class="text-center">	3,2950	  </td>	<td  class="text-center">	3.3037	  </td>	<td  class="text-center">	3.3162	</td>	<td  class="text-center">	3.305	  </td>	<td  class="text-center">	3.3135	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3094	  </td>	<td  class="text-center">	3.3199	</td>	<td  class="text-center">	3.2966	  </td>	<td  class="text-center">	3.315	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.342	  </td>	<td  class="text-center">	3.377	</td>	<td  class="text-center">	3.3106	  </td>	<td  class="text-center">	3.325	</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.33	</td>	<td  class="text-center">	3.35	  </td>	<td  class="text-center">	3.4525	</td>	</tr>
          	<tr>	<td  class="text-center">	10	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3,2975	  </td>	<td  class="text-center">	3,3050	  </td>	<td  class="text-center">	3.305	  </td>	<td  class="text-center">	3.3365	</td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.308	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.3105	</td>	<td  class="text-center">	3.296	  </td>	<td  class="text-center">	3.3135	</td>	<td  class="text-center">	3.355	  </td>	<td  class="text-center">	3.355	</td>	<td  class="text-center">	3.3425	  </td>	<td  class="text-center">	3.3785	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3099	  </td>	<td  class="text-center">	3.3588	</td>	<td  class="text-center">	3.36	  </td>	<td  class="text-center">	3.46	</td>	</tr>
          	<tr>	<td  class="text-center">	11	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3,2955	  </td>	<td  class="text-center">	3,3025	  </td>	<td  class="text-center">	3.3075	  </td>	<td  class="text-center">	3.329	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center">	3.295	  </td>	<td  class="text-center">	3.305	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3438	  </td>	<td  class="text-center">	3.3438	</td>	<td  class="text-center">	3.3436	  </td>	<td  class="text-center">	3.3825	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.315	  </td>	<td  class="text-center">	3.3658	</td>	<td  class="text-center">	3.3525	  </td>	<td  class="text-center">	3.4575	</td>	</tr>
          	<tr>	<td  class="text-center">	12	  </td>	<td  class="text-center">	3,3000	  </td>	<td  class="text-center">	3,3100	  </td>	<td  class="text-center">	3,2891	  </td>	<td  class="text-center">	3,2975	  </td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.37	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center">	3.3145	  </td>	<td  class="text-center">	3.305	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3437	  </td>	<td  class="text-center">	3.3437	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.33	</td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.38	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	</tr>
          	<tr>	<td  class="text-center">	13	  </td>	<td  class="text-center">	3,2885	  </td>	<td  class="text-center">	3,2970	  </td>	<td  class="text-center">	3,3029	  </td>	<td  class="text-center">	3,3134	  </td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.35	</td>	<td  class="text-center">	3.3082	  </td>	<td  class="text-center">	3.3137	</td>	<td  class="text-center">	3.3065	  </td>	<td  class="text-center">	3.3196	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2956	  </td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center">	3.343	  </td>	<td  class="text-center">	3.343	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.315	</td>	<td  class="text-center">	3.32	  </td>	<td  class="text-center">	3.381	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	</tr>
          	<tr>	<td  class="text-center">	14	  </td>	<td  class="text-center">	3,2991	  </td>	<td  class="text-center">	3,3100	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center">	3.302	  </td>	<td  class="text-center">	3.32	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2987	  </td>	<td  class="text-center">	3.3119	</td>	<td  class="text-center">	3.353	  </td>	<td  class="text-center">	3.353	</td>	<td  class="text-center">	3.3444	  </td>	<td  class="text-center">	3.3815	</td>	<td  class="text-center">	3.305	  </td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3555	  </td>	<td  class="text-center">	3.4562	</td>	</tr>
          	<tr>	<td  class="text-center">	15	  </td>	<td  class="text-center">	3,2975	  </td>	<td  class="text-center">	3,3075	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.3075	  </td>	<td  class="text-center">	3.32	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3439	  </td>	<td  class="text-center">	3.3785	</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.34	  </td>	<td  class="text-center">	3.44	</td>	</tr>
          	<tr>	<td  class="text-center">	16	  </td>	<td  class="text-center">	3,3025	  </td>	<td  class="text-center">	3,3100	  </td>	<td  class="text-center">	3,2961	  </td>	<td  class="text-center">	3,3036	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.278	  </td>	<td  class="text-center">	3.2955	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.305	  </td>	<td  class="text-center">	3.3143	</td>	<td  class="text-center">	3.3095	  </td>	<td  class="text-center">	3.321	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3621	  </td>	<td  class="text-center">	3.4645	</td>	</tr>
          	<tr>	<td  class="text-center">	17	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3,2975	  </td>	<td  class="text-center">	3,3075	  </td>	<td  class="text-center">	3.3112	  </td>	<td  class="text-center">	3.3386	</td>	<td  class="text-center">	3.285	  </td>	<td  class="text-center">	3.2915	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.308	  </td>	<td  class="text-center">	3.3175	</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.315	</td>	<td  class="text-center">	3.3508	  </td>	<td  class="text-center">	3.3508	</td>	<td  class="text-center">	3.3465	  </td>	<td  class="text-center">	3.38	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.326	  </td>	<td  class="text-center">	3.385	</td>	<td  class="text-center">	3.3825	  </td>	<td  class="text-center">	3.495	</td>	</tr>
          	<tr>	<td  class="text-center">	18	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3,3000	  </td>	<td  class="text-center">	3,3100	  </td>	<td  class="text-center">	3.314	  </td>	<td  class="text-center">	3.339	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2935	  </td>	<td  class="text-center">	3.306	</td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.3183	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.365	  </td>	<td  class="text-center">	3.365	</td>	<td  class="text-center">	3.3415	  </td>	<td  class="text-center">	3.375	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3225	  </td>	<td  class="text-center">	3.39	</td>	<td  class="text-center">	3.425	  </td>	<td  class="text-center">	3.5475	</td>	</tr>
          	<tr>	<td  class="text-center">	19	  </td>	<td  class="text-center">	3,2962	  </td>	<td  class="text-center">	3,3050	  </td>	<td  class="text-center">	3,3000	  </td>	<td  class="text-center">	3,3100	  </td>	<td  class="text-center">	3.309	  </td>	<td  class="text-center">	3.3681	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2995	  </td>	<td  class="text-center">	3.3138	</td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.3178	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3638	  </td>	<td  class="text-center">	3.3638	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.308	  </td>	<td  class="text-center">	3.3085	</td>	<td  class="text-center">	3.3318	  </td>	<td  class="text-center">	3.41	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	</tr>
          	<tr>	<td  class="text-center">	20	  </td>	<td  class="text-center">	3,3017	  </td>	<td  class="text-center">	3,3110	  </td>	<td  class="text-center">	3,2950	  </td>	<td  class="text-center">	3,3050	  </td>	<td  class="text-center">	3.299	  </td>	<td  class="text-center">	3.334	</td>	<td  class="text-center">	3.295	  </td>	<td  class="text-center">	3.305	</td>	<td  class="text-center">	3.2945	  </td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.3608	  </td>	<td  class="text-center">	3.3608	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.315	</td>	<td  class="text-center">	3.3225	  </td>	<td  class="text-center">	3.395	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	</tr>
          	<tr>	<td  class="text-center">	21	  </td>	<td  class="text-center">	3,2900	  </td>	<td  class="text-center">	3,3001	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2955	  </td>	<td  class="text-center">	3.303	</td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.316	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3042	  </td>	<td  class="text-center">	3.315	</td>	<td  class="text-center">	3.366	  </td>	<td  class="text-center">	3.366	</td>	<td  class="text-center">	3.3257	  </td>	<td  class="text-center">	3.3625	</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.4715	  </td>	<td  class="text-center">	3.55	</td>	</tr>
          	<tr>	<td  class="text-center">	22	  </td>	<td  class="text-center">	3,2950	  </td>	<td  class="text-center">	3,3025	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.297	  </td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center">	3.299	  </td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.3087	  </td>	<td  class="text-center">	3.3187	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.33	  </td>	<td  class="text-center">	3.355	</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.5042	  </td>	<td  class="text-center">	3.5696	</td>	</tr>
          	<tr>	<td  class="text-center">	23	  </td>	<td  class="text-center">	3,2925	  </td>	<td  class="text-center">	3,3012	  </td>	<td  class="text-center">	3,2925	  </td>	<td  class="text-center">	3,3025	  </td>	<td  class="text-center">	3.303	  </td>	<td  class="text-center">	3.3341	</td>	<td  class="text-center">	3.293	  </td>	<td  class="text-center">	3.297	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3088	  </td>	<td  class="text-center">	3.319	</td>	<td  class="text-center">	3.305	  </td>	<td  class="text-center">	3.3175	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3289	  </td>	<td  class="text-center">	3.34	</td>	<td  class="text-center">	3.2925	  </td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center">	3.3325	  </td>	<td  class="text-center">	3.4168	</td>	<td  class="text-center">	3.53	  </td>	<td  class="text-center">	3.5794	</td>	</tr>
          	<tr>	<td  class="text-center">	24	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3,3000	  </td>	<td  class="text-center">	3,3100	  </td>	<td  class="text-center">	3.305	  </td>	<td  class="text-center">	3.325	</td>	<td  class="text-center">	3.3046	  </td>	<td  class="text-center">	3.3132	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.3075	  </td>	<td  class="text-center">	3.3175	</td>	<td  class="text-center">	3.3554	  </td>	<td  class="text-center">	3.3554	</td>	<td  class="text-center">	3.32	  </td>	<td  class="text-center">	3.335	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.326	  </td>	<td  class="text-center">	3.4035	</td>	<td  class="text-center success">	3.5316	  </td>	<td  class="text-center success">	3.5745	</td>	</tr>
          	<tr>	<td  class="text-center">	25	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3,3025	  </td>	<td  class="text-center">	3,3116	  </td>	<td  class="text-center">	3.3083	  </td>	<td  class="text-center">	3.33	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3072	  </td>	<td  class="text-center">	3.3165	</td>	<td  class="text-center">	3.2975	  </td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.36	  </td>	<td  class="text-center">	3.36	</td>	<td  class="text-center">	3.3225	  </td>	<td  class="text-center">	3.335	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.33	  </td>	<td  class="text-center">	3.4075	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	</tr>
          	<tr>	<td  class="text-center">	26	  </td>	<td  class="text-center">	3,2975	  </td>	<td  class="text-center">	3,3050	  </td>	<td  class="text-center">	3,3041	  </td>	<td  class="text-center">	3,3150	  </td>	<td  class="text-center">	3.3075	  </td>	<td  class="text-center">	3.3275	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.305	  </td>	<td  class="text-center">	3.3165	</td>	<td  class="text-center">	3.295	  </td>	<td  class="text-center">	3.305	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3623	  </td>	<td  class="text-center">	3.3623	</td>	<td  class="text-center success">		  </td>	<td  class="text-center">		</td>	<td  class="text-center">	3.29	  </td>	<td  class="text-center">	3.3	</td>	<td  class="text-center">	3.323	  </td>	<td  class="text-center">	3.3949	</td>	<td  class="text-center">		  </td>	<td  class="text-center">		</td>	</tr>
          	<tr>	<td  class="text-center">	27	  </td>	<td  class="text-center">	3,3039	  </td>	<td  class="text-center">	3,3149	  </td>	<td  class="text-center">	3,2925	  </td>	<td  class="text-center">	3,3050	  </td>	<td  class="text-center">	3.31	  </td>	<td  class="text-center">	3.3445	</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.309	</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.31	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">	3.31	  </td>	<td  class="text-center success">	3.3211	</td>	<td  class="text-center">	3.3595	  </td>	<td  class="text-center">	3.3595	</td>	<td  class="text-center success">		  </td>	<td  class="text-center">		</td>	<td  class="text-center">	3.29	  </td>	<td  class="text-center">	3.3	</td>	<td  class="text-center">	3.315	  </td>	<td  class="text-center">	3.395	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	</tr>
          	<tr>	<td  class="text-center">	28	  </td>	<td  class="text-center">	3,2977	  </td>	<td  class="text-center">	3,2924	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.29	  </td>	<td  class="text-center">	3.2955	</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.3143	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">	3.313	  </td>	<td  class="text-center success">	3.323	</td>	<td  class="text-center">	3.355	  </td>	<td  class="text-center">	3.355	</td>	<td  class="text-center">	3.325	  </td>	<td  class="text-center">	3.34	</td>	<td  class="text-center">	3.3037	  </td>	<td  class="text-center">	3.3127	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.535	  </td>	<td  class="text-center">	3.5748	</td>	</tr>
          	<tr>	<td  class="text-center">	29	  </td>	<td  class="text-center">	3,3050	  </td>	<td  class="text-center">	3,3005	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2875	  </td>	<td  class="text-center">	3.295	</td>	<td  class="text-center">	3.295	  </td>	<td  class="text-center">	3.305	</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.3121	</td>	<td  class="text-center success">	3.305	  </td>	<td  class="text-center success">	3.32	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.325	  </td>	<td  class="text-center">	3.3351	</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.315	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.5505	  </td>	<td  class="text-center">	3.58	</td>	</tr>
          	<tr>	<td  class="text-center">	30	  </td>	<td  class="text-center">	3,2875	  </td>	<td  class="text-center">	3,2885	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3.305	  </td>	<td  class="text-center">	3.3325	</td>	<td  class="text-center">	3.2975	  </td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3025	  </td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center success">	3.3025	  </td>	<td  class="text-center success">	3.3205	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.325	  </td>	<td  class="text-center">	3.3385	</td>	<td  class="text-center">	3.3	  </td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.3175	  </td>	<td  class="text-center">	3.405	</td>	<td  class="text-center">	3.5525	  </td>	<td  class="text-center">	3.586	</td>	</tr>
          	<tr>	<td  class="text-center">	31	  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		  </td>	<td  class="text-center">	3.2955	  </td>	<td  class="text-center">	3.3265	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">	3.3112	  </td>	<td  class="text-center success">	3.3278	</td>	<td  class="text-center">	3.3505	  </td>	<td  class="text-center">	3.3505	</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center success">		  </td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.5475	  </td>	<td  class="text-center">	3.58	</td>	</tr>

</tbody>
          <!-- *********** -->
                </table>
              </div>
            </div>
        </div>
      </div>

      <div class="well transparenteClaroTxt">  <!-- Well -->
        <div class="row">
          <div class="col-md-12">
           <div class="table-responsive">
                  <table class="table table-striped  table-bordered table-condensed">
                <!-- ****** -->
                <h3 class="text-center">	Tasa de interés interbancario de equilibrio (T.I.I.E.) 2014	</h3>

            <thead>
            	<tr  class="activoLiMenu">	<th rowspan="2" class="text-center">	publicación en el D.O.F	</th>	<th colspan="2" class="text-center">	Enero </th>				<th colspan="2" class="text-center">	Febrero 	</th>				<th colspan="2" class="text-center">	Marzo 	</th>				<th colspan="2" class="text-center">	Abril 	</th>				<th colspan="2" class="text-center">	Mayo 	</th>				<th colspan="2" class="text-center">	Junio 	</th>				<th colspan="2" class="text-center">	Julio 	</th>				<th colspan="2" class="text-center">	Agosto 	</th>				<th colspan="2" class="text-center">	Septiembre 	</th>				<th colspan="2" class="text-center">	Octubre 	</th>				<th colspan="2" class="text-center">	Noviembre 	</th>				<th colspan="2" class="text-center">	Diciembre 	</th>				</tr>
            	<tr  class="activoLiMenu">				<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	<th  class="text-center">	28 días 	</th>	<th  class="text-center">	91 días	</th>	</tr>
            </thead>
            <tbody class="animEscalarFila">
            	<tr>	<td  class="text-center">	1	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8150	</td>	<td  class="text-center">	3.8100	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center">	3.3175	</td>	<td  class="text-center">	3.3100	</td>	<td  class="text-center">	3.3215	</td>	<td  class="text-center">	3.2860	</td>	<td  class="text-center">	3.2900	</td>	<td  class="text-center">	3.2793	</td>	<td  class="text-center">	3.2928	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2965	</td>	<td  class="text-center">	3.3071	</td>	</tr>
            	<tr>	<td  class="text-center">	2	</td>	<td  class="text-center">	3.7950	</td>	<td  class="text-center">	3.8045	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8125	</td>	<td  class="text-center">	3.8175	</td>	<td  class="text-center">	3.7905	</td>	<td  class="text-center">	3.8100	</td>	<td  class="text-center">	3.7785	</td>	<td  class="text-center">	3.7947	</td>	<td  class="text-center">	3.3077	</td>	<td  class="text-center">	3.3269	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2910	</td>	<td  class="text-center">	3.2972	</td>	<td  class="text-center">	3.2896	</td>	<td  class="text-center">	3.2948	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center">	3.3125	</th>	</tr>
            	<tr>	<td  class="text-center">	3	</td>	<td  class="text-center">	3.7950	</td>	<td  class="text-center">	3.8059	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7919	</td>	<td  class="text-center">	3.8002	</td>	<td  class="text-center">	3.8157	</td>	<td  class="text-center">	3.8077	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8043	</td>	<td  class="text-center">	3.8160	</td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.3264	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2910	</td>	<td  class="text-center">	3.2980	</td>	<td  class="text-center">	3.3000	</td>	<td  class="text-center">	3.3100	</td>	<td  class="text-center">	3.2800	</td>	<td  class="text-center">	3.2900	</td>	<td  class="text-center">	3.2941	</td>	<td  class="text-center">	3.3133	</th>	</tr>
            	<tr>	<td  class="text-center">	4	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7705	</td>	<td  class="text-center">	3.7885	</td>	<td  class="text-center">	3.7956	</td>	<td  class="text-center">	3.8025	</td>	<td  class="text-center">	3.8125	</td>	<td  class="text-center">	3.8125	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8085	</td>	<td  class="text-center">	3.8172	</td>	<td  class="text-center">	3.3068	</td>	<td  class="text-center">	3.3165	</td>	<td  class="text-center">	3.3000	</td>	<td  class="text-center">	3.3115	</td>	<td  class="text-center">	3.2950	</td>	<td  class="text-center">	3.2970	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2938	</td>	<td  class="text-center">	3.3015	</td>	<td  class="text-center">	3.2875	</td>	<td  class="text-center">	3.3016	</th>	</tr>
            	<tr>	<td  class="text-center">	5	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7755	</td>	<td  class="text-center">	3.7892	</td>	<td  class="text-center">	3.7987	</td>	<td  class="text-center">	3.8087	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8000	</td>	<td  class="text-center">	3.8086	</td>	<td  class="text-center">	3.8095	</td>	<td  class="text-center">	3.8190	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.3200	</td>	<td  class="text-center">	3.2826	</td>	<td  class="text-center">	3.2858	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2819	</td>	<td  class="text-center">	3.2982	</td>	<td  class="text-center">	3.2850	</td>	<td  class="text-center">	3.2958	</th>	</tr>
            	<tr>	<td  class="text-center">	6	</td>	<td  class="text-center">	3.7925	</td>	<td  class="text-center">	3.8000	</td>	<td  class="text-center">	3.7643	</td>	<td  class="text-center">	3.7763	</td>	<td  class="text-center">	3.8000	</td>	<td  class="text-center">	3.8070	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8050	</td>	<td  class="text-center">	3.8150	</td>	<td  class="text-center">	3.8085	</td>	<td  class="text-center">	3.8185	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2965	</td>	<td  class="text-center">	3.3083	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2950	</td>	<td  class="text-center">	3.3100	</td>	<td  class="text-center">	3.2755	</td>	<td  class="text-center">	3.2835	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</th>	</tr>
            	<tr>	<td  class="text-center">	7	</td>	<td  class="text-center">	3.7962	</td>	<td  class="text-center">	3.8130	</td>	<td  class="text-center">	3.7671	</td>	<td  class="text-center">	3.7896	</td>	<td  class="text-center">	3.8012	</td>	<td  class="text-center">	3.8087	</td>	<td  class="text-center">	3.8012	</td>	<td  class="text-center">	3.8070	</td>	<td  class="text-center">	3.7980	</td>	<td  class="text-center">	3.8122	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3008	</td>	<td  class="text-center">	3.3083	</td>	<td  class="text-center">	3.2970	</td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2950	</td>	<td  class="text-center">	3.3100	</td>	<td  class="text-center">	3.2798	</td>	<td  class="text-center">	3.2888	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</th>	</tr>
            	<tr>	<td  class="text-center">	8	</td>	<td  class="text-center">	3.7994	</td>	<td  class="text-center">	3.8190	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8054	</td>	<td  class="text-center">	3.8002	</td>	<td  class="text-center">	3.8010	</td>	<td  class="text-center">	3.8148	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2960	</td>	<td  class="text-center">	3.3035	</td>	<td  class="text-center">	3.2935	</td>	<td  class="text-center">	3.3062	</td>	<td  class="text-center">	3.2925	</td>	<td  class="text-center">	3.2925	</td>	<td  class="text-center">	3.3050	</td>	<td  class="text-center">	3.3175	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3075	</th>	</tr>
            	<tr>	<td  class="text-center">	9	</td>	<td  class="text-center">	3.8005	</td>	<td  class="text-center">	3.8163	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8132	</td>	<td  class="text-center">	3.8184	</td>	<td  class="text-center">	3.8149	</td>	<td  class="text-center">	3.8260	</td>	<td  class="text-center">	3.3250	</td>	<td  class="text-center">	3.3400	</td>	<td  class="text-center">	3.2919	</td>	<td  class="text-center">	3.2998	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2925	</td>	<td  class="text-center">	3.2981	</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3087	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3075	</th>	</tr>
            	<tr>	<td  class="text-center">	10	</td>	<td  class="text-center">	3.7927	</td>	<td  class="text-center">	3.8031	</td>	<td  class="text-center">	3.7815	</td>	<td  class="text-center">	3.7910	</td>	<td  class="text-center">	3.8006	</td>	<td  class="text-center">	3.8068	</td>	<td  class="text-center">	3.8087	</td>	<td  class="text-center">	3.8130	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3220	</td>	<td  class="text-center">	3.3295	</td>	<td  class="text-center">	3.2945	</td>	<td  class="text-center">	3.3040	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2926	</td>	<td  class="text-center">	3.2973	</td>	<td  class="text-center">	3.2996	</td>	<td  class="text-center">	3.3028	</td>	<td  class="text-center">	3.2762	</td>	<td  class="text-center">	3.2858	</td>	<td  class="text-center">	3.3007	</td>	<td  class="text-center">	3.3067	</th>	</tr>
            	<tr>	<td  class="text-center">	11	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7840	</td>	<td  class="text-center">	3.7970	</td>	<td  class="text-center">	3.8025	</td>	<td  class="text-center">	3.8100	</td>	<td  class="text-center">	3.8040	</td>	<td  class="text-center">	3.8165	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3160	</td>	<td  class="text-center">	3.3235	</td>	<td  class="text-center">	3.2940	</td>	<td  class="text-center">	3.3035	</td>	<td  class="text-center">	3.2980	</td>	<td  class="text-center">	3.3076	</td>	<td  class="text-center">	3.2818	</td>	<td  class="text-center">	3.2855	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2746	</td>	<td  class="text-center">	3.2819	</td>	<td  class="text-center">	3.2928	</td>	<td  class="text-center">	3.3008	</th>	</tr>
            	<tr>	<td  class="text-center">	12	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7778	</td>	<td  class="text-center">	3.7901	</td>	<td  class="text-center">	3.7937	</td>	<td  class="text-center">	3.8012	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7987	</td>	<td  class="text-center">	3.8087	</td>	<td  class="text-center">	3.3093	</td>	<td  class="text-center">	3.3185	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2972	</td>	<td  class="text-center">	3.3078	</td>	<td  class="text-center">	3.2930	</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2950	</td>	<td  class="text-center">	3.3050	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</th>	</tr>
            	<tr>	<td  class="text-center">	13	</td>	<td  class="text-center">	3.7945	</td>	<td  class="text-center">	3.8165	</td>	<td  class="text-center">	3.7890	</td>	<td  class="text-center">	3.7950	</td>	<td  class="text-center">	3.7918	</td>	<td  class="text-center">	3.8006	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7935	</td>	<td  class="text-center">	3.8120	</td>	<td  class="text-center">	3.3091	</td>	<td  class="text-center">	3.3190	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3010	</td>	<td  class="text-center">	3.3200	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2900	</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.2950	</td>	<td  class="text-center">	3.3050	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</th>	</tr>
            	<tr>	<td  class="text-center">	14	</td>	<td  class="text-center">	3.7972	</td>	<td  class="text-center">	3.8140	</td>	<td  class="text-center">	3.7915	</td>	<td  class="text-center">	3.8040	</td>	<td  class="text-center">	3.8000	</td>	<td  class="text-center">	3.8100	</td>	<td  class="text-center">	3.7960	</td>	<td  class="text-center">	3.8075	</td>	<td  class="text-center">	3.8090	</td>	<td  class="text-center">	3.8200	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3074	</td>	<td  class="text-center">	3.3175	</td>	<td  class="text-center">	3.2941	</td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3031	</td>	<td  class="text-center">	3.3065	</td>	<td  class="text-center">	3.2800	</td>	<td  class="text-center">	3.2880	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</th>	</tr>
            	<tr>	<td  class="text-center">	15	</td>	<td  class="text-center">	3.7933	</td>	<td  class="text-center">	3.8081	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8000	</td>	<td  class="text-center">	3.8075	</td>	<td  class="text-center">	3.8171	</td>	<td  class="text-center">	3.8284	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3095	</td>	<td  class="text-center">	3.3195	</td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.2926	</td>	<td  class="text-center">	3.2973	</td>	<td  class="text-center">	3.2965	</td>	<td  class="text-center">	3.3050	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3075	</th>	</tr>
            	<tr>	<td  class="text-center">	16	</td>	<td  class="text-center">	3.7843	</td>	<td  class="text-center">	3.7943	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8085	</td>	<td  class="text-center">	3.8125	</td>	<td  class="text-center">	3.8075	</td>	<td  class="text-center">	3.8175	</td>	<td  class="text-center">	3.3118	</td>	<td  class="text-center">	3.3169	</td>	<td  class="text-center">	3.2972	</td>	<td  class="text-center">	3.3097	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2886	</td>	<td  class="text-center">	3.2943	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3075	</th>	</tr>
            	<tr>	<td  class="text-center">	17	</td>	<td  class="text-center">	3.7825	</td>	<td  class="text-center">	3.8005	</td>	<td  class="text-center">	3.7872	</td>	<td  class="text-center">	3.8040	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center">	3.3150	</td>	<td  class="text-center">	3.2970	</td>	<td  class="text-center">	3.3123	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3065	</td>	<td  class="text-center">	3.3137	</td>	<td  class="text-center">	3.2835	</td>	<td  class="text-center">	3.2906	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2996	</td>	<td  class="text-center">	3.3093	</th>	</tr>
            	<tr>	<td  class="text-center">	18	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7950	</td>	<td  class="text-center">	3.8100	</td>	<td  class="text-center">	3.8075	</td>	<td  class="text-center">	3.8175	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3095	</td>	<td  class="text-center">	3.3150	</td>	<td  class="text-center">	3.2932	</td>	<td  class="text-center">	3.3061	</td>	<td  class="text-center">	3.2983	</td>	<td  class="text-center">	3.3063	</td>	<td  class="text-center">	3.2900	</td>	<td  class="text-center">	3.3000	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2800	</td>	<td  class="text-center">	3.2891	</td>	<td  class="text-center">	3.2996	</td>	<td  class="text-center">	3.3096	</th>	</tr>
            	<tr>	<td  class="text-center">	19	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8025	</td>	<td  class="text-center">	3.8150	</td>	<td  class="text-center">	3.7950	</td>	<td  class="text-center">	3.8025	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8084	</td>	<td  class="text-center">	3.8184	</td>	<td  class="text-center">	3.3100	</td>	<td  class="text-center">	3.3176	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2925	</td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2775	</td>	<td  class="text-center">	3.2887	</td>	<td  class="text-center">	3.2996	</td>	<td  class="text-center">	3.3101	</th>	</tr>
            	<tr>	<td  class="text-center">	20	</td>	<td  class="text-center">	3.7665	</td>	<td  class="text-center">	3.7918	</td>	<td  class="text-center">	3.7930	</td>	<td  class="text-center">	3.8050	</td>	<td  class="text-center">	3.8000	</td>	<td  class="text-center">	3.8100	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7948	</td>	<td  class="text-center">	3.8093	</td>	<td  class="text-center">	3.3100	</td>	<td  class="text-center">	3.3175	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2864	</td>	<td  class="text-center">	3.2935	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2850	</td>	<td  class="text-center">	3.2950	</td>	<td  class="text-center">	3.2775	</td>	<td  class="text-center">	3.2850	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</th>	</tr>
            	<tr>	<td  class="text-center">	21	</td>	<td  class="text-center">	3.7615	</td>	<td  class="text-center">	3.7769	</td>	<td  class="text-center">	3.7935	</td>	<td  class="text-center">	3.8000	</td>	<td  class="text-center">	3.8012	</td>	<td  class="text-center">	3.8112	</td>	<td  class="text-center">	3.7950	</td>	<td  class="text-center">	3.8075	</td>	<td  class="text-center">	3.8000	</td>	<td  class="text-center">	3.8153	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2821	</td>	<td  class="text-center">	3.3024	</td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center">	3.2977	</td>	<td  class="text-center">	3.3050	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</th>	</tr>
            	<tr>	<td  class="text-center">	22	</td>	<td  class="text-center">	3.7670	</td>	<td  class="text-center">	3.7825	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8110	</td>	<td  class="text-center">	3.8218	</td>	<td  class="text-center">	3.8085	</td>	<td  class="text-center">	3.8210	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2891	</td>	<td  class="text-center">	3.3050	</td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center">	3.3000	</td>	<td  class="text-center">	3.3100	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3125	</th>	</tr>
            	<tr>	<td  class="text-center">	23	</td>	<td  class="text-center">	3.7771	</td>	<td  class="text-center">	3.7862	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8075	</td>	<td  class="text-center">	3.8175	</td>	<td  class="text-center">	3.8072	</td>	<td  class="text-center">	3.8230	</td>	<td  class="text-center">	3.3184	</td>	<td  class="text-center">	3.3284	</td>	<td  class="text-center">	3.2850	</td>	<td  class="text-center">	3.2978	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2865	</td>	<td  class="text-center">	3.2955	</td>	<td  class="text-center">	3.2950	</td>	<td  class="text-center">	3.3050	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3112	</td>	<td  class="text-center">	3.3250	</th>	</tr>
            	<tr>	<td  class="text-center">	24	</td>	<td  class="text-center">	3.7645	</td>	<td  class="text-center">	3.7825	</td>	<td  class="text-center">	3.7975	</td>	<td  class="text-center">	3.8075	</td>	<td  class="text-center">	3.8062	</td>	<td  class="text-center">	3.8110	</td>	<td  class="text-center">	3.8145	</td>	<td  class="text-center">	3.8287	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3100	</td>	<td  class="text-center">	3.3175	</td>	<td  class="text-center">	3.2875	</td>	<td  class="text-center">	3.3000	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2820	</td>	<td  class="text-center">	3.2916	</td>	<td  class="text-center">	3.2875	</td>	<td  class="text-center">	3.2973	</td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.3120	</td>	<td  class="text-center">	3.3195	</th>	</tr>
            	<tr>	<td  class="text-center">	25	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7937	</td>	<td  class="text-center">	3.8062	</td>	<td  class="text-center">	3.8050	</td>	<td  class="text-center">	3.8100	</td>	<td  class="text-center">	3.8022	</td>	<td  class="text-center">	3.8143	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center">	3.3150	</td>	<td  class="text-center">	3.2936	</td>	<td  class="text-center">	3.3048	</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3036	</td>	<td  class="text-center">	3.2825	</td>	<td  class="text-center">	3.2925	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center success">		</td>	<td  class="text-center">		</th>	</tr>
            	<tr>	<td  class="text-center">	26	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8025	</td>	<td  class="text-center">	3.8125	</td>	<td  class="text-center">	3.8125	</td>	<td  class="text-center">	3.8175	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8160	</td>	<td  class="text-center">	3.8297	</td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.3225	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center">	3.3125	</td>	<td  class="text-center">	3.2768	</td>	<td  class="text-center">	3.2841	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2904	</td>	<td  class="text-center">	3.2996	</td>	<td  class="text-center">	3.3060	</td>	<td  class="text-center">	3.3150	</th>	</tr>
            	<tr>	<td  class="text-center">	27	</td>	<td  class="text-center">	3.7650	</td>	<td  class="text-center">	3.7855	</td>	<td  class="text-center">	3.7962	</td>	<td  class="text-center">	3.8062	</td>	<td  class="text-center">	3.8067	</td>	<td  class="text-center">	3.8163	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7915	</td>	<td  class="text-center">	3.8087	</td>	<td  class="text-center">	3.3087	</td>	<td  class="text-center">	3.3212	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2925	</td>	<td  class="text-center">	3.2936	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2838	</td>	<td  class="text-center">	3.2923	</td>	<td  class="text-center">	3.2957	</td>	<td  class="text-center">	3.3051	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</th>	</tr>
            	<tr>	<td  class="text-center">	28	</td>	<td  class="text-center">	3.7650	</td>	<td  class="text-center">	3.7805	</td>	<td  class="text-center">	3.7917	</td>	<td  class="text-center">	3.8035	</td>	<td  class="text-center">	3.8033	</td>	<td  class="text-center">	3.8031	</td>	<td  class="text-center">	3.8152	</td>	<td  class="text-center">	3.8260	</td>	<td  class="text-center">	3.8085	</td>	<td  class="text-center">	3.8160	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2910	</td>	<td  class="text-center">	3.3019	</td>	<td  class="text-center">	3.2951	</td>	<td  class="text-center">	3.2990	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2950	</td>	<td  class="text-center">	3.3050	</td>	<td  class="text-center">	3.3085	</td>	<td  class="text-center">	3.3185	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</th>	</tr>
            	<tr>	<td  class="text-center">	29	</td>	<td  class="text-center">	3.7650	</td>	<td  class="text-center">	3.7789	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7956	</td>	<td  class="text-center">	3.8075	</td>	<td  class="text-center">	3.7968	</td>	<td  class="text-center">	3.8128	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2886	</td>	<td  class="text-center">	3.2984	</td>	<td  class="text-center">	3.2975	</td>	<td  class="text-center">	3.3025	</td>	<td  class="text-center">	3.2741	</td>	<td  class="text-center">	3.2820	</td>	<td  class="text-center">	3.2903	</td>	<td  class="text-center">	3.2991	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3020	</td>	<td  class="text-center">	3.3126	</th>	</tr>
            	<tr>	<td  class="text-center">	30	</td>	<td  class="text-center">	3.7726	</td>	<td  class="text-center">	3.7756	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.7950	</td>	<td  class="text-center">	3.8067	</td>	<td  class="text-center">	3.7858	</td>	<td  class="text-center">	3.8014	</td>	<td  class="text-center">	3.3050	</td>	<td  class="text-center">	3.3200	</td>	<td  class="text-center">	3.3023	</td>	<td  class="text-center">	3.3120	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2916	</td>	<td  class="text-center">	3.2970	</td>	<td  class="text-center">	3.2762	</td>	<td  class="text-center">	3.2841	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3066	</td>	<td  class="text-center">	3.3110	</th>	</tr>
            	<tr>	<td  class="text-center">	31	</td>	<td  class="text-center">	3.7761	</td>	<td  class="text-center">	3.7818	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.8125	</td>	<td  class="text-center">	3.8080	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3075	</td>	<td  class="text-center">	3.3175	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.2810	</td>	<td  class="text-center">	3.2900	</td>	<td  class="text-center success">		</td>	<td  class="text-center success">		</td>	<td  class="text-center">	3.3110	</td>	<td  class="text-center">	3.3155	</th>	</tr>

            </tbody>
<!-- **************** -->
      </table>
    </div>
  </div>
</div>
</div>

              </div>

          </div>
        </div>



      <script src="../../../../js/jquery.js"></script>
      <script src="../../../../js/bootstrap.min.js"></script>
      <?php include ("../../../../seccionesVista/piePagina.php"); ?>


      <script>
        $('#navInfoteca').addClass('activoLi');
        //jQuery to collapse the navbar on scroll
        $(window).scroll(function() {
            if ($(".navbar").offset().top > 50) {
                $(".navbar-fixed-top").addClass("top-nav-collapse");
            } else {
                $(".navbar-fixed-top").removeClass("top-nav-collapse");
            }
        });
      </script>
      <script>
  $('#ulFi').addClass('in');
  $('#liTiie').addClass('activoBorde');
</script>

  </body>
</html>
